time_resolution: NS
topology: /cluster/home/tabaeias/scion-simulator/topology/topology_2000_geo_rel_energy_br_idx_no_routers.xml
output: /cluster/scratch/tabaeias/green_beaconing_results.txt
simulation_duration: 130min
NUM_CORE: 128
beacon_service:
  policy: green_beaconing
  br_br_energy_file: /cluster/scratch/tabaeias/br_br_energy.txt
  period: 10min
  expiration_period: 6h
  first_beaconing: 0min
  last_beaconing: 120min
