// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/hidden_segment/v1/hidden_segment.proto
// Protobuf C++ Version: 4.24.0-main

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
#include "proto/control_plane/v1/seg.pb.h"
#include "proto/crypto/v1/signed.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
namespace proto {
namespace hidden_segment {
namespace v1 {
class AuthoritativeHiddenSegmentsRequest;
struct AuthoritativeHiddenSegmentsRequestDefaultTypeInternal;
extern AuthoritativeHiddenSegmentsRequestDefaultTypeInternal _AuthoritativeHiddenSegmentsRequest_default_instance_;
class AuthoritativeHiddenSegmentsResponse;
struct AuthoritativeHiddenSegmentsResponseDefaultTypeInternal;
extern AuthoritativeHiddenSegmentsResponseDefaultTypeInternal _AuthoritativeHiddenSegmentsResponse_default_instance_;
class AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse;
struct AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal;
extern AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal _AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse_default_instance_;
class HiddenSegmentRegistrationRequest;
struct HiddenSegmentRegistrationRequestDefaultTypeInternal;
extern HiddenSegmentRegistrationRequestDefaultTypeInternal _HiddenSegmentRegistrationRequest_default_instance_;
class HiddenSegmentRegistrationRequestBody;
struct HiddenSegmentRegistrationRequestBodyDefaultTypeInternal;
extern HiddenSegmentRegistrationRequestBodyDefaultTypeInternal _HiddenSegmentRegistrationRequestBody_default_instance_;
class HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse;
struct HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUseDefaultTypeInternal;
extern HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUseDefaultTypeInternal _HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse_default_instance_;
class HiddenSegmentRegistrationResponse;
struct HiddenSegmentRegistrationResponseDefaultTypeInternal;
extern HiddenSegmentRegistrationResponseDefaultTypeInternal _HiddenSegmentRegistrationResponse_default_instance_;
class HiddenSegmentsRequest;
struct HiddenSegmentsRequestDefaultTypeInternal;
extern HiddenSegmentsRequestDefaultTypeInternal _HiddenSegmentsRequest_default_instance_;
class HiddenSegmentsResponse;
struct HiddenSegmentsResponseDefaultTypeInternal;
extern HiddenSegmentsResponseDefaultTypeInternal _HiddenSegmentsResponse_default_instance_;
class HiddenSegmentsResponse_SegmentsEntry_DoNotUse;
struct HiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal;
extern HiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal _HiddenSegmentsResponse_SegmentsEntry_DoNotUse_default_instance_;
class Segments;
struct SegmentsDefaultTypeInternal;
extern SegmentsDefaultTypeInternal _Segments_default_instance_;
}  // namespace v1
}  // namespace hidden_segment
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {
namespace hidden_segment {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class HiddenSegmentsRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.hidden_segment.v1.HiddenSegmentsRequest) */ {
 public:
  inline HiddenSegmentsRequest() : HiddenSegmentsRequest(nullptr) {}
  ~HiddenSegmentsRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR HiddenSegmentsRequest(::google::protobuf::internal::ConstantInitialized);

  inline HiddenSegmentsRequest(const HiddenSegmentsRequest& from)
      : HiddenSegmentsRequest(nullptr, from) {}
  HiddenSegmentsRequest(HiddenSegmentsRequest&& from) noexcept
    : HiddenSegmentsRequest() {
    *this = ::std::move(from);
  }

  inline HiddenSegmentsRequest& operator=(const HiddenSegmentsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HiddenSegmentsRequest& operator=(HiddenSegmentsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HiddenSegmentsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HiddenSegmentsRequest* internal_default_instance() {
    return reinterpret_cast<const HiddenSegmentsRequest*>(
               &_HiddenSegmentsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(HiddenSegmentsRequest& a, HiddenSegmentsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HiddenSegmentsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HiddenSegmentsRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HiddenSegmentsRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HiddenSegmentsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HiddenSegmentsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const HiddenSegmentsRequest& from) {
    HiddenSegmentsRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(HiddenSegmentsRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "proto.hidden_segment.v1.HiddenSegmentsRequest";
  }
  protected:
  explicit HiddenSegmentsRequest(::google::protobuf::Arena* arena);
  HiddenSegmentsRequest(::google::protobuf::Arena* arena, const HiddenSegmentsRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGroupIdsFieldNumber = 1,
    kDstIsdAsFieldNumber = 2,
  };
  // repeated uint64 group_ids = 1;
  int group_ids_size() const;
  private:
  int _internal_group_ids_size() const;

  public:
  void clear_group_ids() ;
  ::uint64_t group_ids(int index) const;
  void set_group_ids(int index, ::uint64_t value);
  void add_group_ids(::uint64_t value);
  const ::google::protobuf::RepeatedField<::uint64_t>& group_ids() const;
  ::google::protobuf::RepeatedField<::uint64_t>* mutable_group_ids();

  private:
  const ::google::protobuf::RepeatedField<::uint64_t>& _internal_group_ids() const;
  ::google::protobuf::RepeatedField<::uint64_t>* _internal_mutable_group_ids();

  public:
  // uint64 dst_isd_as = 2;
  void clear_dst_isd_as() ;
  ::uint64_t dst_isd_as() const;
  void set_dst_isd_as(::uint64_t value);

  private:
  ::uint64_t _internal_dst_isd_as() const;
  void _internal_set_dst_isd_as(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.hidden_segment.v1.HiddenSegmentsRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedField<::uint64_t> group_ids_;
    mutable ::google::protobuf::internal::CachedSize _group_ids_cached_byte_size_;
    ::uint64_t dst_isd_as_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};// -------------------------------------------------------------------

class HiddenSegmentRegistrationResponse final :
    public ::google::protobuf::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:proto.hidden_segment.v1.HiddenSegmentRegistrationResponse) */ {
 public:
  inline HiddenSegmentRegistrationResponse() : HiddenSegmentRegistrationResponse(nullptr) {}
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR HiddenSegmentRegistrationResponse(::google::protobuf::internal::ConstantInitialized);

  inline HiddenSegmentRegistrationResponse(const HiddenSegmentRegistrationResponse& from)
      : HiddenSegmentRegistrationResponse(nullptr, from) {}
  HiddenSegmentRegistrationResponse(HiddenSegmentRegistrationResponse&& from) noexcept
    : HiddenSegmentRegistrationResponse() {
    *this = ::std::move(from);
  }

  inline HiddenSegmentRegistrationResponse& operator=(const HiddenSegmentRegistrationResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline HiddenSegmentRegistrationResponse& operator=(HiddenSegmentRegistrationResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HiddenSegmentRegistrationResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const HiddenSegmentRegistrationResponse* internal_default_instance() {
    return reinterpret_cast<const HiddenSegmentRegistrationResponse*>(
               &_HiddenSegmentRegistrationResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(HiddenSegmentRegistrationResponse& a, HiddenSegmentRegistrationResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(HiddenSegmentRegistrationResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HiddenSegmentRegistrationResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HiddenSegmentRegistrationResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HiddenSegmentRegistrationResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const HiddenSegmentRegistrationResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const HiddenSegmentRegistrationResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "proto.hidden_segment.v1.HiddenSegmentRegistrationResponse";
  }
  protected:
  explicit HiddenSegmentRegistrationResponse(::google::protobuf::Arena* arena);
  HiddenSegmentRegistrationResponse(::google::protobuf::Arena* arena, const HiddenSegmentRegistrationResponse& from);
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.hidden_segment.v1.HiddenSegmentRegistrationResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};// -------------------------------------------------------------------

class HiddenSegmentRegistrationRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest) */ {
 public:
  inline HiddenSegmentRegistrationRequest() : HiddenSegmentRegistrationRequest(nullptr) {}
  ~HiddenSegmentRegistrationRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR HiddenSegmentRegistrationRequest(::google::protobuf::internal::ConstantInitialized);

  inline HiddenSegmentRegistrationRequest(const HiddenSegmentRegistrationRequest& from)
      : HiddenSegmentRegistrationRequest(nullptr, from) {}
  HiddenSegmentRegistrationRequest(HiddenSegmentRegistrationRequest&& from) noexcept
    : HiddenSegmentRegistrationRequest() {
    *this = ::std::move(from);
  }

  inline HiddenSegmentRegistrationRequest& operator=(const HiddenSegmentRegistrationRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HiddenSegmentRegistrationRequest& operator=(HiddenSegmentRegistrationRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HiddenSegmentRegistrationRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HiddenSegmentRegistrationRequest* internal_default_instance() {
    return reinterpret_cast<const HiddenSegmentRegistrationRequest*>(
               &_HiddenSegmentRegistrationRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HiddenSegmentRegistrationRequest& a, HiddenSegmentRegistrationRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HiddenSegmentRegistrationRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HiddenSegmentRegistrationRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HiddenSegmentRegistrationRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HiddenSegmentRegistrationRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HiddenSegmentRegistrationRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const HiddenSegmentRegistrationRequest& from) {
    HiddenSegmentRegistrationRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(HiddenSegmentRegistrationRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "proto.hidden_segment.v1.HiddenSegmentRegistrationRequest";
  }
  protected:
  explicit HiddenSegmentRegistrationRequest(::google::protobuf::Arena* arena);
  HiddenSegmentRegistrationRequest(::google::protobuf::Arena* arena, const HiddenSegmentRegistrationRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSignedRequestFieldNumber = 1,
  };
  // .proto.crypto.v1.SignedMessage signed_request = 1;
  bool has_signed_request() const;
  void clear_signed_request() ;
  const ::proto::crypto::v1::SignedMessage& signed_request() const;
  PROTOBUF_NODISCARD ::proto::crypto::v1::SignedMessage* release_signed_request();
  ::proto::crypto::v1::SignedMessage* mutable_signed_request();
  void set_allocated_signed_request(::proto::crypto::v1::SignedMessage* value);
  void unsafe_arena_set_allocated_signed_request(::proto::crypto::v1::SignedMessage* value);
  ::proto::crypto::v1::SignedMessage* unsafe_arena_release_signed_request();

  private:
  const ::proto::crypto::v1::SignedMessage& _internal_signed_request() const;
  ::proto::crypto::v1::SignedMessage* _internal_mutable_signed_request();

  public:
  // @@protoc_insertion_point(class_scope:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::proto::crypto::v1::SignedMessage* signed_request_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};// -------------------------------------------------------------------

class AuthoritativeHiddenSegmentsRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest) */ {
 public:
  inline AuthoritativeHiddenSegmentsRequest() : AuthoritativeHiddenSegmentsRequest(nullptr) {}
  ~AuthoritativeHiddenSegmentsRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AuthoritativeHiddenSegmentsRequest(::google::protobuf::internal::ConstantInitialized);

  inline AuthoritativeHiddenSegmentsRequest(const AuthoritativeHiddenSegmentsRequest& from)
      : AuthoritativeHiddenSegmentsRequest(nullptr, from) {}
  AuthoritativeHiddenSegmentsRequest(AuthoritativeHiddenSegmentsRequest&& from) noexcept
    : AuthoritativeHiddenSegmentsRequest() {
    *this = ::std::move(from);
  }

  inline AuthoritativeHiddenSegmentsRequest& operator=(const AuthoritativeHiddenSegmentsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthoritativeHiddenSegmentsRequest& operator=(AuthoritativeHiddenSegmentsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthoritativeHiddenSegmentsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuthoritativeHiddenSegmentsRequest* internal_default_instance() {
    return reinterpret_cast<const AuthoritativeHiddenSegmentsRequest*>(
               &_AuthoritativeHiddenSegmentsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(AuthoritativeHiddenSegmentsRequest& a, AuthoritativeHiddenSegmentsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AuthoritativeHiddenSegmentsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthoritativeHiddenSegmentsRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthoritativeHiddenSegmentsRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AuthoritativeHiddenSegmentsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AuthoritativeHiddenSegmentsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const AuthoritativeHiddenSegmentsRequest& from) {
    AuthoritativeHiddenSegmentsRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AuthoritativeHiddenSegmentsRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest";
  }
  protected:
  explicit AuthoritativeHiddenSegmentsRequest(::google::protobuf::Arena* arena);
  AuthoritativeHiddenSegmentsRequest(::google::protobuf::Arena* arena, const AuthoritativeHiddenSegmentsRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSignedRequestFieldNumber = 1,
  };
  // .proto.crypto.v1.SignedMessage signed_request = 1;
  bool has_signed_request() const;
  void clear_signed_request() ;
  const ::proto::crypto::v1::SignedMessage& signed_request() const;
  PROTOBUF_NODISCARD ::proto::crypto::v1::SignedMessage* release_signed_request();
  ::proto::crypto::v1::SignedMessage* mutable_signed_request();
  void set_allocated_signed_request(::proto::crypto::v1::SignedMessage* value);
  void unsafe_arena_set_allocated_signed_request(::proto::crypto::v1::SignedMessage* value);
  ::proto::crypto::v1::SignedMessage* unsafe_arena_release_signed_request();

  private:
  const ::proto::crypto::v1::SignedMessage& _internal_signed_request() const;
  ::proto::crypto::v1::SignedMessage* _internal_mutable_signed_request();

  public:
  // @@protoc_insertion_point(class_scope:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::proto::crypto::v1::SignedMessage* signed_request_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};// -------------------------------------------------------------------

class Segments final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.hidden_segment.v1.Segments) */ {
 public:
  inline Segments() : Segments(nullptr) {}
  ~Segments() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Segments(::google::protobuf::internal::ConstantInitialized);

  inline Segments(const Segments& from)
      : Segments(nullptr, from) {}
  Segments(Segments&& from) noexcept
    : Segments() {
    *this = ::std::move(from);
  }

  inline Segments& operator=(const Segments& from) {
    CopyFrom(from);
    return *this;
  }
  inline Segments& operator=(Segments&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Segments& default_instance() {
    return *internal_default_instance();
  }
  static inline const Segments* internal_default_instance() {
    return reinterpret_cast<const Segments*>(
               &_Segments_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Segments& a, Segments& b) {
    a.Swap(&b);
  }
  inline void Swap(Segments* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Segments* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Segments* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Segments>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Segments& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Segments& from) {
    Segments::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Segments* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "proto.hidden_segment.v1.Segments";
  }
  protected:
  explicit Segments(::google::protobuf::Arena* arena);
  Segments(::google::protobuf::Arena* arena, const Segments& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSegmentsFieldNumber = 1,
  };
  // repeated .proto.control_plane.v1.PathSegment segments = 1;
  int segments_size() const;
  private:
  int _internal_segments_size() const;

  public:
  void clear_segments() ;
  ::proto::control_plane::v1::PathSegment* mutable_segments(int index);
  ::google::protobuf::RepeatedPtrField< ::proto::control_plane::v1::PathSegment >*
      mutable_segments();
  private:
  const ::google::protobuf::RepeatedPtrField<::proto::control_plane::v1::PathSegment>& _internal_segments() const;
  ::google::protobuf::RepeatedPtrField<::proto::control_plane::v1::PathSegment>* _internal_mutable_segments();
  public:
  const ::proto::control_plane::v1::PathSegment& segments(int index) const;
  ::proto::control_plane::v1::PathSegment* add_segments();
  const ::google::protobuf::RepeatedPtrField< ::proto::control_plane::v1::PathSegment >&
      segments() const;
  // @@protoc_insertion_point(class_scope:proto.hidden_segment.v1.Segments)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::proto::control_plane::v1::PathSegment > segments_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};// -------------------------------------------------------------------

class HiddenSegmentsResponse_SegmentsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          HiddenSegmentsResponse_SegmentsEntry_DoNotUse, ::int32_t, ::proto::hidden_segment::v1::Segments,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      HiddenSegmentsResponse_SegmentsEntry_DoNotUse, ::int32_t, ::proto::hidden_segment::v1::Segments,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  HiddenSegmentsResponse_SegmentsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HiddenSegmentsResponse_SegmentsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit HiddenSegmentsResponse_SegmentsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const HiddenSegmentsResponse_SegmentsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const HiddenSegmentsResponse_SegmentsEntry_DoNotUse*>(
        &_HiddenSegmentsResponse_SegmentsEntry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};
// -------------------------------------------------------------------

class HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse, ::int32_t, ::proto::hidden_segment::v1::Segments,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse, ::int32_t, ::proto::hidden_segment::v1::Segments,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse*>(
        &_HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};
// -------------------------------------------------------------------

class AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse, ::int32_t, ::proto::hidden_segment::v1::Segments,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse, ::int32_t, ::proto::hidden_segment::v1::Segments,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse*>(
        &_AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};
// -------------------------------------------------------------------

class HiddenSegmentsResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.hidden_segment.v1.HiddenSegmentsResponse) */ {
 public:
  inline HiddenSegmentsResponse() : HiddenSegmentsResponse(nullptr) {}
  ~HiddenSegmentsResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR HiddenSegmentsResponse(::google::protobuf::internal::ConstantInitialized);

  inline HiddenSegmentsResponse(const HiddenSegmentsResponse& from)
      : HiddenSegmentsResponse(nullptr, from) {}
  HiddenSegmentsResponse(HiddenSegmentsResponse&& from) noexcept
    : HiddenSegmentsResponse() {
    *this = ::std::move(from);
  }

  inline HiddenSegmentsResponse& operator=(const HiddenSegmentsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline HiddenSegmentsResponse& operator=(HiddenSegmentsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HiddenSegmentsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const HiddenSegmentsResponse* internal_default_instance() {
    return reinterpret_cast<const HiddenSegmentsResponse*>(
               &_HiddenSegmentsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(HiddenSegmentsResponse& a, HiddenSegmentsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(HiddenSegmentsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HiddenSegmentsResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HiddenSegmentsResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HiddenSegmentsResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HiddenSegmentsResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const HiddenSegmentsResponse& from) {
    HiddenSegmentsResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(HiddenSegmentsResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "proto.hidden_segment.v1.HiddenSegmentsResponse";
  }
  protected:
  explicit HiddenSegmentsResponse(::google::protobuf::Arena* arena);
  HiddenSegmentsResponse(::google::protobuf::Arena* arena, const HiddenSegmentsResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kSegmentsFieldNumber = 1,
  };
  // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
  int segments_size() const;
  private:
  int _internal_segments_size() const;

  public:
  void clear_segments() ;
  const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& segments() const;
  ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* mutable_segments();

  private:
  const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& _internal_segments() const;
  ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* _internal_mutable_segments();

  public:
  // @@protoc_insertion_point(class_scope:proto.hidden_segment.v1.HiddenSegmentsResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::MapField<HiddenSegmentsResponse_SegmentsEntry_DoNotUse, ::int32_t, ::proto::hidden_segment::v1::Segments,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        segments_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};// -------------------------------------------------------------------

class HiddenSegmentRegistrationRequestBody final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody) */ {
 public:
  inline HiddenSegmentRegistrationRequestBody() : HiddenSegmentRegistrationRequestBody(nullptr) {}
  ~HiddenSegmentRegistrationRequestBody() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR HiddenSegmentRegistrationRequestBody(::google::protobuf::internal::ConstantInitialized);

  inline HiddenSegmentRegistrationRequestBody(const HiddenSegmentRegistrationRequestBody& from)
      : HiddenSegmentRegistrationRequestBody(nullptr, from) {}
  HiddenSegmentRegistrationRequestBody(HiddenSegmentRegistrationRequestBody&& from) noexcept
    : HiddenSegmentRegistrationRequestBody() {
    *this = ::std::move(from);
  }

  inline HiddenSegmentRegistrationRequestBody& operator=(const HiddenSegmentRegistrationRequestBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline HiddenSegmentRegistrationRequestBody& operator=(HiddenSegmentRegistrationRequestBody&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HiddenSegmentRegistrationRequestBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const HiddenSegmentRegistrationRequestBody* internal_default_instance() {
    return reinterpret_cast<const HiddenSegmentRegistrationRequestBody*>(
               &_HiddenSegmentRegistrationRequestBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(HiddenSegmentRegistrationRequestBody& a, HiddenSegmentRegistrationRequestBody& b) {
    a.Swap(&b);
  }
  inline void Swap(HiddenSegmentRegistrationRequestBody* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HiddenSegmentRegistrationRequestBody* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HiddenSegmentRegistrationRequestBody* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HiddenSegmentRegistrationRequestBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HiddenSegmentRegistrationRequestBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const HiddenSegmentRegistrationRequestBody& from) {
    HiddenSegmentRegistrationRequestBody::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(HiddenSegmentRegistrationRequestBody* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody";
  }
  protected:
  explicit HiddenSegmentRegistrationRequestBody(::google::protobuf::Arena* arena);
  HiddenSegmentRegistrationRequestBody(::google::protobuf::Arena* arena, const HiddenSegmentRegistrationRequestBody& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kSegmentsFieldNumber = 1,
    kGroupIdFieldNumber = 2,
  };
  // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
  int segments_size() const;
  private:
  int _internal_segments_size() const;

  public:
  void clear_segments() ;
  const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& segments() const;
  ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* mutable_segments();

  private:
  const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& _internal_segments() const;
  ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* _internal_mutable_segments();

  public:
  // uint64 group_id = 2;
  void clear_group_id() ;
  ::uint64_t group_id() const;
  void set_group_id(::uint64_t value);

  private:
  ::uint64_t _internal_group_id() const;
  void _internal_set_group_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 2, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::MapField<HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse, ::int32_t, ::proto::hidden_segment::v1::Segments,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        segments_;
    ::uint64_t group_id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};// -------------------------------------------------------------------

class AuthoritativeHiddenSegmentsResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse) */ {
 public:
  inline AuthoritativeHiddenSegmentsResponse() : AuthoritativeHiddenSegmentsResponse(nullptr) {}
  ~AuthoritativeHiddenSegmentsResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AuthoritativeHiddenSegmentsResponse(::google::protobuf::internal::ConstantInitialized);

  inline AuthoritativeHiddenSegmentsResponse(const AuthoritativeHiddenSegmentsResponse& from)
      : AuthoritativeHiddenSegmentsResponse(nullptr, from) {}
  AuthoritativeHiddenSegmentsResponse(AuthoritativeHiddenSegmentsResponse&& from) noexcept
    : AuthoritativeHiddenSegmentsResponse() {
    *this = ::std::move(from);
  }

  inline AuthoritativeHiddenSegmentsResponse& operator=(const AuthoritativeHiddenSegmentsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthoritativeHiddenSegmentsResponse& operator=(AuthoritativeHiddenSegmentsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthoritativeHiddenSegmentsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuthoritativeHiddenSegmentsResponse* internal_default_instance() {
    return reinterpret_cast<const AuthoritativeHiddenSegmentsResponse*>(
               &_AuthoritativeHiddenSegmentsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(AuthoritativeHiddenSegmentsResponse& a, AuthoritativeHiddenSegmentsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AuthoritativeHiddenSegmentsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthoritativeHiddenSegmentsResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthoritativeHiddenSegmentsResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AuthoritativeHiddenSegmentsResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AuthoritativeHiddenSegmentsResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const AuthoritativeHiddenSegmentsResponse& from) {
    AuthoritativeHiddenSegmentsResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AuthoritativeHiddenSegmentsResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse";
  }
  protected:
  explicit AuthoritativeHiddenSegmentsResponse(::google::protobuf::Arena* arena);
  AuthoritativeHiddenSegmentsResponse(::google::protobuf::Arena* arena, const AuthoritativeHiddenSegmentsResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kSegmentsFieldNumber = 1,
  };
  // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
  int segments_size() const;
  private:
  int _internal_segments_size() const;

  public:
  void clear_segments() ;
  const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& segments() const;
  ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* mutable_segments();

  private:
  const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& _internal_segments() const;
  ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* _internal_mutable_segments();

  public:
  // @@protoc_insertion_point(class_scope:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::MapField<AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse, ::int32_t, ::proto::hidden_segment::v1::Segments,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        segments_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Segments

// repeated .proto.control_plane.v1.PathSegment segments = 1;
inline int Segments::_internal_segments_size() const {
  return _internal_segments().size();
}
inline int Segments::segments_size() const {
  return _internal_segments_size();
}
inline ::proto::control_plane::v1::PathSegment* Segments::mutable_segments(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:proto.hidden_segment.v1.Segments.segments)
  return _internal_mutable_segments()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::proto::control_plane::v1::PathSegment>* Segments::mutable_segments()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:proto.hidden_segment.v1.Segments.segments)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_segments();
}
inline const ::proto::control_plane::v1::PathSegment& Segments::segments(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.hidden_segment.v1.Segments.segments)
  return _internal_segments().Get(index);
}
inline ::proto::control_plane::v1::PathSegment* Segments::add_segments() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::proto::control_plane::v1::PathSegment* _add = _internal_mutable_segments()->Add();
  // @@protoc_insertion_point(field_add:proto.hidden_segment.v1.Segments.segments)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::proto::control_plane::v1::PathSegment>& Segments::segments() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:proto.hidden_segment.v1.Segments.segments)
  return _internal_segments();
}
inline const ::google::protobuf::RepeatedPtrField<::proto::control_plane::v1::PathSegment>&
Segments::_internal_segments() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.segments_;
}
inline ::google::protobuf::RepeatedPtrField<::proto::control_plane::v1::PathSegment>*
Segments::_internal_mutable_segments() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.segments_;
}

// -------------------------------------------------------------------

// HiddenSegmentRegistrationRequest

// .proto.crypto.v1.SignedMessage signed_request = 1;
inline bool HiddenSegmentRegistrationRequest::has_signed_request() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.signed_request_ != nullptr);
  return value;
}
inline const ::proto::crypto::v1::SignedMessage& HiddenSegmentRegistrationRequest::_internal_signed_request() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::proto::crypto::v1::SignedMessage* p = _impl_.signed_request_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::crypto::v1::SignedMessage&>(::proto::crypto::v1::_SignedMessage_default_instance_);
}
inline const ::proto::crypto::v1::SignedMessage& HiddenSegmentRegistrationRequest::signed_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest.signed_request)
  return _internal_signed_request();
}
inline void HiddenSegmentRegistrationRequest::unsafe_arena_set_allocated_signed_request(::proto::crypto::v1::SignedMessage* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.signed_request_);
  }
  _impl_.signed_request_ = reinterpret_cast<::proto::crypto::v1::SignedMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest.signed_request)
}
inline ::proto::crypto::v1::SignedMessage* HiddenSegmentRegistrationRequest::release_signed_request() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::proto::crypto::v1::SignedMessage* released = _impl_.signed_request_;
  _impl_.signed_request_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::proto::crypto::v1::SignedMessage* HiddenSegmentRegistrationRequest::unsafe_arena_release_signed_request() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest.signed_request)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::proto::crypto::v1::SignedMessage* temp = _impl_.signed_request_;
  _impl_.signed_request_ = nullptr;
  return temp;
}
inline ::proto::crypto::v1::SignedMessage* HiddenSegmentRegistrationRequest::_internal_mutable_signed_request() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.signed_request_ == nullptr) {
    auto* p = CreateMaybeMessage<::proto::crypto::v1::SignedMessage>(GetArena());
    _impl_.signed_request_ = reinterpret_cast<::proto::crypto::v1::SignedMessage*>(p);
  }
  return _impl_.signed_request_;
}
inline ::proto::crypto::v1::SignedMessage* HiddenSegmentRegistrationRequest::mutable_signed_request() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::proto::crypto::v1::SignedMessage* _msg = _internal_mutable_signed_request();
  // @@protoc_insertion_point(field_mutable:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest.signed_request)
  return _msg;
}
inline void HiddenSegmentRegistrationRequest::set_allocated_signed_request(::proto::crypto::v1::SignedMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.signed_request_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.signed_request_ = reinterpret_cast<::proto::crypto::v1::SignedMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest.signed_request)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// HiddenSegmentRegistrationRequestBody

// map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
inline int HiddenSegmentRegistrationRequestBody::_internal_segments_size() const {
  return _internal_segments().size();
}
inline int HiddenSegmentRegistrationRequestBody::segments_size() const {
  return _internal_segments_size();
}
inline void HiddenSegmentRegistrationRequestBody::clear_segments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.segments_.Clear();
}
inline const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& HiddenSegmentRegistrationRequestBody::_internal_segments() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.segments_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& HiddenSegmentRegistrationRequestBody::segments() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody.segments)
  return _internal_segments();
}
inline ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* HiddenSegmentRegistrationRequestBody::_internal_mutable_segments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.segments_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* HiddenSegmentRegistrationRequestBody::mutable_segments() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody.segments)
  return _internal_mutable_segments();
}

// uint64 group_id = 2;
inline void HiddenSegmentRegistrationRequestBody::clear_group_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.group_id_ = ::uint64_t{0u};
}
inline ::uint64_t HiddenSegmentRegistrationRequestBody::group_id() const {
  // @@protoc_insertion_point(field_get:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody.group_id)
  return _internal_group_id();
}
inline void HiddenSegmentRegistrationRequestBody::set_group_id(::uint64_t value) {
  _internal_set_group_id(value);
  // @@protoc_insertion_point(field_set:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody.group_id)
}
inline ::uint64_t HiddenSegmentRegistrationRequestBody::_internal_group_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.group_id_;
}
inline void HiddenSegmentRegistrationRequestBody::_internal_set_group_id(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.group_id_ = value;
}

// -------------------------------------------------------------------

// HiddenSegmentRegistrationResponse

// -------------------------------------------------------------------

// HiddenSegmentsRequest

// repeated uint64 group_ids = 1;
inline int HiddenSegmentsRequest::_internal_group_ids_size() const {
  return _internal_group_ids().size();
}
inline int HiddenSegmentsRequest::group_ids_size() const {
  return _internal_group_ids_size();
}
inline void HiddenSegmentsRequest::clear_group_ids() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.group_ids_.Clear();
}
inline ::uint64_t HiddenSegmentsRequest::group_ids(int index) const {
  // @@protoc_insertion_point(field_get:proto.hidden_segment.v1.HiddenSegmentsRequest.group_ids)
  return _internal_group_ids().Get(index);
}
inline void HiddenSegmentsRequest::set_group_ids(int index, ::uint64_t value) {
  _internal_mutable_group_ids()->Set(index, value);
  // @@protoc_insertion_point(field_set:proto.hidden_segment.v1.HiddenSegmentsRequest.group_ids)
}
inline void HiddenSegmentsRequest::add_group_ids(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_group_ids()->Add(value);
  // @@protoc_insertion_point(field_add:proto.hidden_segment.v1.HiddenSegmentsRequest.group_ids)
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& HiddenSegmentsRequest::group_ids() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:proto.hidden_segment.v1.HiddenSegmentsRequest.group_ids)
  return _internal_group_ids();
}
inline ::google::protobuf::RepeatedField<::uint64_t>* HiddenSegmentsRequest::mutable_group_ids()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:proto.hidden_segment.v1.HiddenSegmentsRequest.group_ids)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_group_ids();
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& HiddenSegmentsRequest::_internal_group_ids()
    const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.group_ids_;
}
inline ::google::protobuf::RepeatedField<::uint64_t>* HiddenSegmentsRequest::_internal_mutable_group_ids() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.group_ids_;
}

// uint64 dst_isd_as = 2;
inline void HiddenSegmentsRequest::clear_dst_isd_as() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.dst_isd_as_ = ::uint64_t{0u};
}
inline ::uint64_t HiddenSegmentsRequest::dst_isd_as() const {
  // @@protoc_insertion_point(field_get:proto.hidden_segment.v1.HiddenSegmentsRequest.dst_isd_as)
  return _internal_dst_isd_as();
}
inline void HiddenSegmentsRequest::set_dst_isd_as(::uint64_t value) {
  _internal_set_dst_isd_as(value);
  // @@protoc_insertion_point(field_set:proto.hidden_segment.v1.HiddenSegmentsRequest.dst_isd_as)
}
inline ::uint64_t HiddenSegmentsRequest::_internal_dst_isd_as() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.dst_isd_as_;
}
inline void HiddenSegmentsRequest::_internal_set_dst_isd_as(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.dst_isd_as_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// HiddenSegmentsResponse

// map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
inline int HiddenSegmentsResponse::_internal_segments_size() const {
  return _internal_segments().size();
}
inline int HiddenSegmentsResponse::segments_size() const {
  return _internal_segments_size();
}
inline void HiddenSegmentsResponse::clear_segments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.segments_.Clear();
}
inline const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& HiddenSegmentsResponse::_internal_segments() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.segments_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& HiddenSegmentsResponse::segments() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:proto.hidden_segment.v1.HiddenSegmentsResponse.segments)
  return _internal_segments();
}
inline ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* HiddenSegmentsResponse::_internal_mutable_segments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.segments_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* HiddenSegmentsResponse::mutable_segments() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:proto.hidden_segment.v1.HiddenSegmentsResponse.segments)
  return _internal_mutable_segments();
}

// -------------------------------------------------------------------

// AuthoritativeHiddenSegmentsRequest

// .proto.crypto.v1.SignedMessage signed_request = 1;
inline bool AuthoritativeHiddenSegmentsRequest::has_signed_request() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.signed_request_ != nullptr);
  return value;
}
inline const ::proto::crypto::v1::SignedMessage& AuthoritativeHiddenSegmentsRequest::_internal_signed_request() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::proto::crypto::v1::SignedMessage* p = _impl_.signed_request_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::crypto::v1::SignedMessage&>(::proto::crypto::v1::_SignedMessage_default_instance_);
}
inline const ::proto::crypto::v1::SignedMessage& AuthoritativeHiddenSegmentsRequest::signed_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest.signed_request)
  return _internal_signed_request();
}
inline void AuthoritativeHiddenSegmentsRequest::unsafe_arena_set_allocated_signed_request(::proto::crypto::v1::SignedMessage* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.signed_request_);
  }
  _impl_.signed_request_ = reinterpret_cast<::proto::crypto::v1::SignedMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest.signed_request)
}
inline ::proto::crypto::v1::SignedMessage* AuthoritativeHiddenSegmentsRequest::release_signed_request() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::proto::crypto::v1::SignedMessage* released = _impl_.signed_request_;
  _impl_.signed_request_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::proto::crypto::v1::SignedMessage* AuthoritativeHiddenSegmentsRequest::unsafe_arena_release_signed_request() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest.signed_request)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::proto::crypto::v1::SignedMessage* temp = _impl_.signed_request_;
  _impl_.signed_request_ = nullptr;
  return temp;
}
inline ::proto::crypto::v1::SignedMessage* AuthoritativeHiddenSegmentsRequest::_internal_mutable_signed_request() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.signed_request_ == nullptr) {
    auto* p = CreateMaybeMessage<::proto::crypto::v1::SignedMessage>(GetArena());
    _impl_.signed_request_ = reinterpret_cast<::proto::crypto::v1::SignedMessage*>(p);
  }
  return _impl_.signed_request_;
}
inline ::proto::crypto::v1::SignedMessage* AuthoritativeHiddenSegmentsRequest::mutable_signed_request() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::proto::crypto::v1::SignedMessage* _msg = _internal_mutable_signed_request();
  // @@protoc_insertion_point(field_mutable:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest.signed_request)
  return _msg;
}
inline void AuthoritativeHiddenSegmentsRequest::set_allocated_signed_request(::proto::crypto::v1::SignedMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.signed_request_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.signed_request_ = reinterpret_cast<::proto::crypto::v1::SignedMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest.signed_request)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// AuthoritativeHiddenSegmentsResponse

// map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
inline int AuthoritativeHiddenSegmentsResponse::_internal_segments_size() const {
  return _internal_segments().size();
}
inline int AuthoritativeHiddenSegmentsResponse::segments_size() const {
  return _internal_segments_size();
}
inline void AuthoritativeHiddenSegmentsResponse::clear_segments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.segments_.Clear();
}
inline const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& AuthoritativeHiddenSegmentsResponse::_internal_segments() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.segments_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>& AuthoritativeHiddenSegmentsResponse::segments() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse.segments)
  return _internal_segments();
}
inline ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* AuthoritativeHiddenSegmentsResponse::_internal_mutable_segments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.segments_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>* AuthoritativeHiddenSegmentsResponse::mutable_segments() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse.segments)
  return _internal_mutable_segments();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace hidden_segment
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_2epb_2eh
