// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/hidden_segment/v1/hidden_segment.proto

#include "proto/hidden_segment/v1/hidden_segment.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {
namespace hidden_segment {
namespace v1 {

inline constexpr HiddenSegmentsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : group_ids_{},
        _group_ids_cached_byte_size_{0},
        dst_isd_as_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HiddenSegmentsRequest::HiddenSegmentsRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HiddenSegmentsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HiddenSegmentsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HiddenSegmentsRequestDefaultTypeInternal() {}
  union {
    HiddenSegmentsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HiddenSegmentsRequestDefaultTypeInternal _HiddenSegmentsRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR HiddenSegmentRegistrationResponse::HiddenSegmentRegistrationResponse(::_pbi::ConstantInitialized) {}
struct HiddenSegmentRegistrationResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HiddenSegmentRegistrationResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HiddenSegmentRegistrationResponseDefaultTypeInternal() {}
  union {
    HiddenSegmentRegistrationResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HiddenSegmentRegistrationResponseDefaultTypeInternal _HiddenSegmentRegistrationResponse_default_instance_;

inline constexpr HiddenSegmentRegistrationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        signed_request_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR HiddenSegmentRegistrationRequest::HiddenSegmentRegistrationRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HiddenSegmentRegistrationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HiddenSegmentRegistrationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HiddenSegmentRegistrationRequestDefaultTypeInternal() {}
  union {
    HiddenSegmentRegistrationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HiddenSegmentRegistrationRequestDefaultTypeInternal _HiddenSegmentRegistrationRequest_default_instance_;

inline constexpr AuthoritativeHiddenSegmentsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        signed_request_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR AuthoritativeHiddenSegmentsRequest::AuthoritativeHiddenSegmentsRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthoritativeHiddenSegmentsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthoritativeHiddenSegmentsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthoritativeHiddenSegmentsRequestDefaultTypeInternal() {}
  union {
    AuthoritativeHiddenSegmentsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthoritativeHiddenSegmentsRequestDefaultTypeInternal _AuthoritativeHiddenSegmentsRequest_default_instance_;

inline constexpr Segments::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : segments_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Segments::Segments(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SegmentsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SegmentsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SegmentsDefaultTypeInternal() {}
  union {
    Segments _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SegmentsDefaultTypeInternal _Segments_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR HiddenSegmentsResponse_SegmentsEntry_DoNotUse::HiddenSegmentsResponse_SegmentsEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct HiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    HiddenSegmentsResponse_SegmentsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal _HiddenSegmentsResponse_SegmentsEntry_DoNotUse_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse::HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUseDefaultTypeInternal _HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse::AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUseDefaultTypeInternal _AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse_default_instance_;

inline constexpr HiddenSegmentsResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : segments_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HiddenSegmentsResponse::HiddenSegmentsResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HiddenSegmentsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HiddenSegmentsResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HiddenSegmentsResponseDefaultTypeInternal() {}
  union {
    HiddenSegmentsResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HiddenSegmentsResponseDefaultTypeInternal _HiddenSegmentsResponse_default_instance_;

inline constexpr HiddenSegmentRegistrationRequestBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : segments_{},
        group_id_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HiddenSegmentRegistrationRequestBody::HiddenSegmentRegistrationRequestBody(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HiddenSegmentRegistrationRequestBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HiddenSegmentRegistrationRequestBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HiddenSegmentRegistrationRequestBodyDefaultTypeInternal() {}
  union {
    HiddenSegmentRegistrationRequestBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HiddenSegmentRegistrationRequestBodyDefaultTypeInternal _HiddenSegmentRegistrationRequestBody_default_instance_;

inline constexpr AuthoritativeHiddenSegmentsResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : segments_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AuthoritativeHiddenSegmentsResponse::AuthoritativeHiddenSegmentsResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthoritativeHiddenSegmentsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthoritativeHiddenSegmentsResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthoritativeHiddenSegmentsResponseDefaultTypeInternal() {}
  union {
    AuthoritativeHiddenSegmentsResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthoritativeHiddenSegmentsResponseDefaultTypeInternal _AuthoritativeHiddenSegmentsResponse_default_instance_;
}  // namespace v1
}  // namespace hidden_segment
}  // namespace proto
static ::_pb::Metadata file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[11];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto = nullptr;
const ::uint32_t TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::Segments, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::Segments, _impl_.segments_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequest, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequest, _impl_.signed_request_),
    0,
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequestBody, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequestBody, _impl_.segments_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequestBody, _impl_.group_id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentRegistrationResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentsRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentsRequest, _impl_.group_ids_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentsRequest, _impl_.dst_isd_as_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentsResponse_SegmentsEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentsResponse_SegmentsEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentsResponse_SegmentsEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentsResponse_SegmentsEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentsResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::HiddenSegmentsResponse, _impl_.segments_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsRequest, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsRequest, _impl_.signed_request_),
    0,
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsResponse, _impl_.segments_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::proto::hidden_segment::v1::Segments)},
        {9, 18, -1, sizeof(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequest)},
        {19, 29, -1, sizeof(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse)},
        {31, -1, -1, sizeof(::proto::hidden_segment::v1::HiddenSegmentRegistrationRequestBody)},
        {41, -1, -1, sizeof(::proto::hidden_segment::v1::HiddenSegmentRegistrationResponse)},
        {49, -1, -1, sizeof(::proto::hidden_segment::v1::HiddenSegmentsRequest)},
        {59, 69, -1, sizeof(::proto::hidden_segment::v1::HiddenSegmentsResponse_SegmentsEntry_DoNotUse)},
        {71, -1, -1, sizeof(::proto::hidden_segment::v1::HiddenSegmentsResponse)},
        {80, 89, -1, sizeof(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsRequest)},
        {90, 100, -1, sizeof(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse)},
        {102, -1, -1, sizeof(::proto::hidden_segment::v1::AuthoritativeHiddenSegmentsResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::proto::hidden_segment::v1::_Segments_default_instance_._instance,
    &::proto::hidden_segment::v1::_HiddenSegmentRegistrationRequest_default_instance_._instance,
    &::proto::hidden_segment::v1::_HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse_default_instance_._instance,
    &::proto::hidden_segment::v1::_HiddenSegmentRegistrationRequestBody_default_instance_._instance,
    &::proto::hidden_segment::v1::_HiddenSegmentRegistrationResponse_default_instance_._instance,
    &::proto::hidden_segment::v1::_HiddenSegmentsRequest_default_instance_._instance,
    &::proto::hidden_segment::v1::_HiddenSegmentsResponse_SegmentsEntry_DoNotUse_default_instance_._instance,
    &::proto::hidden_segment::v1::_HiddenSegmentsResponse_default_instance_._instance,
    &::proto::hidden_segment::v1::_AuthoritativeHiddenSegmentsRequest_default_instance_._instance,
    &::proto::hidden_segment::v1::_AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse_default_instance_._instance,
    &::proto::hidden_segment::v1::_AuthoritativeHiddenSegmentsResponse_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n,proto/hidden_segment/v1/hidden_segment"
    ".proto\022\027proto.hidden_segment.v1\032 proto/c"
    "ontrol_plane/v1/seg.proto\032\034proto/crypto/"
    "v1/signed.proto\"A\n\010Segments\0225\n\010segments\030"
    "\001 \003(\0132#.proto.control_plane.v1.PathSegme"
    "nt\"Z\n HiddenSegmentRegistrationRequest\0226"
    "\n\016signed_request\030\001 \001(\0132\036.proto.crypto.v1"
    ".SignedMessage\"\353\001\n$HiddenSegmentRegistra"
    "tionRequestBody\022]\n\010segments\030\001 \003(\0132K.prot"
    "o.hidden_segment.v1.HiddenSegmentRegistr"
    "ationRequestBody.SegmentsEntry\022\020\n\010group_"
    "id\030\002 \001(\004\032R\n\rSegmentsEntry\022\013\n\003key\030\001 \001(\005\0220"
    "\n\005value\030\002 \001(\0132!.proto.hidden_segment.v1."
    "Segments:\0028\001\"#\n!HiddenSegmentRegistratio"
    "nResponse\">\n\025HiddenSegmentsRequest\022\021\n\tgr"
    "oup_ids\030\001 \003(\004\022\022\n\ndst_isd_as\030\002 \001(\004\"\275\001\n\026Hi"
    "ddenSegmentsResponse\022O\n\010segments\030\001 \003(\0132="
    ".proto.hidden_segment.v1.HiddenSegmentsR"
    "esponse.SegmentsEntry\032R\n\rSegmentsEntry\022\013"
    "\n\003key\030\001 \001(\005\0220\n\005value\030\002 \001(\0132!.proto.hidde"
    "n_segment.v1.Segments:\0028\001\"\\\n\"Authoritati"
    "veHiddenSegmentsRequest\0226\n\016signed_reques"
    "t\030\001 \001(\0132\036.proto.crypto.v1.SignedMessage\""
    "\327\001\n#AuthoritativeHiddenSegmentsResponse\022"
    "\\\n\010segments\030\001 \003(\0132J.proto.hidden_segment"
    ".v1.AuthoritativeHiddenSegmentsResponse."
    "SegmentsEntry\032R\n\rSegmentsEntry\022\013\n\003key\030\001 "
    "\001(\005\0220\n\005value\030\002 \001(\0132!.proto.hidden_segmen"
    "t.v1.Segments:\0028\0012\271\001\n HiddenSegmentRegis"
    "trationService\022\224\001\n\031HiddenSegmentRegistra"
    "tion\0229.proto.hidden_segment.v1.HiddenSeg"
    "mentRegistrationRequest\032:.proto.hidden_s"
    "egment.v1.HiddenSegmentRegistrationRespo"
    "nse\"\0002\221\001\n\032HiddenSegmentLookupService\022s\n\016"
    "HiddenSegments\022..proto.hidden_segment.v1"
    ".HiddenSegmentsRequest\032/.proto.hidden_se"
    "gment.v1.HiddenSegmentsResponse\"\0002\306\001\n\'Au"
    "thoritativeHiddenSegmentLookupService\022\232\001"
    "\n\033AuthoritativeHiddenSegments\022;.proto.hi"
    "dden_segment.v1.AuthoritativeHiddenSegme"
    "ntsRequest\032<.proto.hidden_segment.v1.Aut"
    "horitativeHiddenSegmentsResponse\"\000B6Z4gi"
    "thub.com/scionproto/scion/pkg/proto/hidd"
    "en_segmentb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_deps[2] =
    {
        &::descriptor_table_proto_2fcontrol_5fplane_2fv1_2fseg_2eproto,
        &::descriptor_table_proto_2fcrypto_2fv1_2fsigned_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto = {
    false,
    false,
    1738,
    descriptor_table_protodef_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto,
    "proto/hidden_segment/v1/hidden_segment.proto",
    &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
    descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_deps,
    2,
    11,
    schemas,
    file_default_instances,
    TableStruct_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto::offsets,
    file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto,
    file_level_enum_descriptors_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto,
    file_level_service_descriptors_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter() {
  return &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto(&descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto);
namespace proto {
namespace hidden_segment {
namespace v1 {
// ===================================================================

class Segments::_Internal {
 public:
};

void Segments::clear_segments() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.segments_.Clear();
}
Segments::Segments(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.hidden_segment.v1.Segments)
}
inline PROTOBUF_NDEBUG_INLINE Segments::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : segments_{visibility, arena, from.segments_},
        _cached_size_{0} {}

Segments::Segments(
    ::google::protobuf::Arena* arena,
    const Segments& from)
    : ::google::protobuf::Message(arena) {
  Segments* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:proto.hidden_segment.v1.Segments)
}
inline PROTOBUF_NDEBUG_INLINE Segments::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : segments_{visibility, arena},
        _cached_size_{0} {}

inline void Segments::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Segments::~Segments() {
  // @@protoc_insertion_point(destructor:proto.hidden_segment.v1.Segments)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Segments::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Segments::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.hidden_segment.v1.Segments)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.segments_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Segments::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Segments::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Segments_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .proto.control_plane.v1.PathSegment segments = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Segments, _impl_.segments_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .proto.control_plane.v1.PathSegment segments = 1;
    {PROTOBUF_FIELD_OFFSET(Segments, _impl_.segments_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::proto::control_plane::v1::PathSegment>()},
  }}, {{
  }},
};

::uint8_t* Segments::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.hidden_segment.v1.Segments)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .proto.control_plane.v1.PathSegment segments = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_segments_size()); i < n; i++) {
    const auto& repfield = this->_internal_segments().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.hidden_segment.v1.Segments)
  return target;
}

::size_t Segments::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.hidden_segment.v1.Segments)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .proto.control_plane.v1.PathSegment segments = 1;
  total_size += 1UL * this->_internal_segments_size();
  for (const auto& msg : this->_internal_segments()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Segments::_class_data_ = {
    Segments::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Segments::GetClassData() const {
  return &_class_data_;
}

void Segments::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Segments*>(&to_msg);
  auto& from = static_cast<const Segments&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.hidden_segment.v1.Segments)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_segments()->MergeFrom(
      from._internal_segments());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Segments::CopyFrom(const Segments& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.hidden_segment.v1.Segments)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Segments::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Segments::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Segments::InternalSwap(Segments* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.segments_.InternalSwap(&other->_impl_.segments_);
}

::google::protobuf::Metadata Segments::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[0]);
}
// ===================================================================

class HiddenSegmentRegistrationRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<HiddenSegmentRegistrationRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(HiddenSegmentRegistrationRequest, _impl_._has_bits_);
  static const ::proto::crypto::v1::SignedMessage& signed_request(const HiddenSegmentRegistrationRequest* msg);
  static void set_has_signed_request(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::proto::crypto::v1::SignedMessage& HiddenSegmentRegistrationRequest::_Internal::signed_request(const HiddenSegmentRegistrationRequest* msg) {
  return *msg->_impl_.signed_request_;
}
void HiddenSegmentRegistrationRequest::clear_signed_request() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.signed_request_ != nullptr) _impl_.signed_request_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
HiddenSegmentRegistrationRequest::HiddenSegmentRegistrationRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
}
inline PROTOBUF_NDEBUG_INLINE HiddenSegmentRegistrationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

HiddenSegmentRegistrationRequest::HiddenSegmentRegistrationRequest(
    ::google::protobuf::Arena* arena,
    const HiddenSegmentRegistrationRequest& from)
    : ::google::protobuf::Message(arena) {
  HiddenSegmentRegistrationRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.signed_request_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::proto::crypto::v1::SignedMessage>(arena, *from._impl_.signed_request_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
}
inline PROTOBUF_NDEBUG_INLINE HiddenSegmentRegistrationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void HiddenSegmentRegistrationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.signed_request_ = {};
}
HiddenSegmentRegistrationRequest::~HiddenSegmentRegistrationRequest() {
  // @@protoc_insertion_point(destructor:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HiddenSegmentRegistrationRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete _impl_.signed_request_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void HiddenSegmentRegistrationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.signed_request_ != nullptr);
    _impl_.signed_request_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* HiddenSegmentRegistrationRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> HiddenSegmentRegistrationRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HiddenSegmentRegistrationRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_HiddenSegmentRegistrationRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .proto.crypto.v1.SignedMessage signed_request = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(HiddenSegmentRegistrationRequest, _impl_.signed_request_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .proto.crypto.v1.SignedMessage signed_request = 1;
    {PROTOBUF_FIELD_OFFSET(HiddenSegmentRegistrationRequest, _impl_.signed_request_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::proto::crypto::v1::SignedMessage>()},
  }}, {{
  }},
};

::uint8_t* HiddenSegmentRegistrationRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .proto.crypto.v1.SignedMessage signed_request = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::signed_request(this),
        _Internal::signed_request(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
  return target;
}

::size_t HiddenSegmentRegistrationRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .proto.crypto.v1.SignedMessage signed_request = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.signed_request_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData HiddenSegmentRegistrationRequest::_class_data_ = {
    HiddenSegmentRegistrationRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* HiddenSegmentRegistrationRequest::GetClassData() const {
  return &_class_data_;
}

void HiddenSegmentRegistrationRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<HiddenSegmentRegistrationRequest*>(&to_msg);
  auto& from = static_cast<const HiddenSegmentRegistrationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_signed_request()->::proto::crypto::v1::SignedMessage::MergeFrom(
        from._internal_signed_request());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HiddenSegmentRegistrationRequest::CopyFrom(const HiddenSegmentRegistrationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool HiddenSegmentRegistrationRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* HiddenSegmentRegistrationRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void HiddenSegmentRegistrationRequest::InternalSwap(HiddenSegmentRegistrationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.signed_request_, other->_impl_.signed_request_);
}

::google::protobuf::Metadata HiddenSegmentRegistrationRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[1]);
}
// ===================================================================

HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse::HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse() {}
HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse::HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
::google::protobuf::Metadata HiddenSegmentRegistrationRequestBody_SegmentsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[2]);
}
// ===================================================================

class HiddenSegmentRegistrationRequestBody::_Internal {
 public:
};

HiddenSegmentRegistrationRequestBody::HiddenSegmentRegistrationRequestBody(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE HiddenSegmentRegistrationRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : segments_{visibility, arena, from.segments_},
        _cached_size_{0} {}

HiddenSegmentRegistrationRequestBody::HiddenSegmentRegistrationRequestBody(
    ::google::protobuf::Arena* arena,
    const HiddenSegmentRegistrationRequestBody& from)
    : ::google::protobuf::Message(arena) {
  HiddenSegmentRegistrationRequestBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.group_id_ = from._impl_.group_id_;

  // @@protoc_insertion_point(copy_constructor:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE HiddenSegmentRegistrationRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : segments_{visibility, arena},
        _cached_size_{0} {}

inline void HiddenSegmentRegistrationRequestBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.group_id_ = {};
}
HiddenSegmentRegistrationRequestBody::~HiddenSegmentRegistrationRequestBody() {
  // @@protoc_insertion_point(destructor:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HiddenSegmentRegistrationRequestBody::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void HiddenSegmentRegistrationRequestBody::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.segments_.Clear();
  _impl_.group_id_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* HiddenSegmentRegistrationRequestBody::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2> HiddenSegmentRegistrationRequestBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_HiddenSegmentRegistrationRequestBody_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint64 group_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(HiddenSegmentRegistrationRequestBody, _impl_.group_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(HiddenSegmentRegistrationRequestBody, _impl_.group_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
    {PROTOBUF_FIELD_OFFSET(HiddenSegmentRegistrationRequestBody, _impl_.segments_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // uint64 group_id = 2;
    {PROTOBUF_FIELD_OFFSET(HiddenSegmentRegistrationRequestBody, _impl_.group_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(HiddenSegmentRegistrationRequestBody()._impl_.segments_)>(
        1, 0, 0, 5,
        11)},
    {::_pbi::TcParser::CreateInArenaStorageCb<::proto::hidden_segment::v1::Segments>},
  }}, {{
  }},
};

::uint8_t* HiddenSegmentRegistrationRequestBody::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
  if (!_internal_segments().empty()) {
    using MapType = ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>;
    using WireHelper = _pbi::MapEntryFuncs<::int32_t, ::proto::hidden_segment::v1::Segments,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = _internal_segments();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    }
  }

  // uint64 group_id = 2;
  if (this->_internal_group_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_group_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
  return target;
}

::size_t HiddenSegmentRegistrationRequestBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_segments_size());
  for (const auto& entry : _internal_segments()) {
    total_size += _pbi::MapEntryFuncs<::int32_t, ::proto::hidden_segment::v1::Segments,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
  }
  // uint64 group_id = 2;
  if (this->_internal_group_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_group_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData HiddenSegmentRegistrationRequestBody::_class_data_ = {
    HiddenSegmentRegistrationRequestBody::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* HiddenSegmentRegistrationRequestBody::GetClassData() const {
  return &_class_data_;
}

void HiddenSegmentRegistrationRequestBody::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<HiddenSegmentRegistrationRequestBody*>(&to_msg);
  auto& from = static_cast<const HiddenSegmentRegistrationRequestBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.segments_.MergeFrom(from._impl_.segments_);
  if (from._internal_group_id() != 0) {
    _this->_internal_set_group_id(from._internal_group_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HiddenSegmentRegistrationRequestBody::CopyFrom(const HiddenSegmentRegistrationRequestBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.hidden_segment.v1.HiddenSegmentRegistrationRequestBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool HiddenSegmentRegistrationRequestBody::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* HiddenSegmentRegistrationRequestBody::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void HiddenSegmentRegistrationRequestBody::InternalSwap(HiddenSegmentRegistrationRequestBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.segments_.InternalSwap(&other->_impl_.segments_);
        swap(_impl_.group_id_, other->_impl_.group_id_);
}

::google::protobuf::Metadata HiddenSegmentRegistrationRequestBody::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[3]);
}
// ===================================================================

class HiddenSegmentRegistrationResponse::_Internal {
 public:
};

HiddenSegmentRegistrationResponse::HiddenSegmentRegistrationResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:proto.hidden_segment.v1.HiddenSegmentRegistrationResponse)
}
HiddenSegmentRegistrationResponse::HiddenSegmentRegistrationResponse(
    ::google::protobuf::Arena* arena,
    const HiddenSegmentRegistrationResponse& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  HiddenSegmentRegistrationResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:proto.hidden_segment.v1.HiddenSegmentRegistrationResponse)
}









::google::protobuf::Metadata HiddenSegmentRegistrationResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[4]);
}
// ===================================================================

class HiddenSegmentsRequest::_Internal {
 public:
};

HiddenSegmentsRequest::HiddenSegmentsRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.hidden_segment.v1.HiddenSegmentsRequest)
}
inline PROTOBUF_NDEBUG_INLINE HiddenSegmentsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : group_ids_{visibility, arena, from.group_ids_},
        _group_ids_cached_byte_size_{0},
        _cached_size_{0} {}

HiddenSegmentsRequest::HiddenSegmentsRequest(
    ::google::protobuf::Arena* arena,
    const HiddenSegmentsRequest& from)
    : ::google::protobuf::Message(arena) {
  HiddenSegmentsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.dst_isd_as_ = from._impl_.dst_isd_as_;

  // @@protoc_insertion_point(copy_constructor:proto.hidden_segment.v1.HiddenSegmentsRequest)
}
inline PROTOBUF_NDEBUG_INLINE HiddenSegmentsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : group_ids_{visibility, arena},
        _group_ids_cached_byte_size_{0},
        _cached_size_{0} {}

inline void HiddenSegmentsRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.dst_isd_as_ = {};
}
HiddenSegmentsRequest::~HiddenSegmentsRequest() {
  // @@protoc_insertion_point(destructor:proto.hidden_segment.v1.HiddenSegmentsRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HiddenSegmentsRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void HiddenSegmentsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.hidden_segment.v1.HiddenSegmentsRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.group_ids_.Clear();
  _impl_.dst_isd_as_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* HiddenSegmentsRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> HiddenSegmentsRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_HiddenSegmentsRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint64 dst_isd_as = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(HiddenSegmentsRequest, _impl_.dst_isd_as_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(HiddenSegmentsRequest, _impl_.dst_isd_as_)}},
    // repeated uint64 group_ids = 1;
    {::_pbi::TcParser::FastV64P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(HiddenSegmentsRequest, _impl_.group_ids_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated uint64 group_ids = 1;
    {PROTOBUF_FIELD_OFFSET(HiddenSegmentsRequest, _impl_.group_ids_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt64)},
    // uint64 dst_isd_as = 2;
    {PROTOBUF_FIELD_OFFSET(HiddenSegmentsRequest, _impl_.dst_isd_as_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* HiddenSegmentsRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.hidden_segment.v1.HiddenSegmentsRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated uint64 group_ids = 1;
  {
    int byte_size = _impl_._group_ids_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt64Packed(
          1, _internal_group_ids(), byte_size, target);
    }
  }

  // uint64 dst_isd_as = 2;
  if (this->_internal_dst_isd_as() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_dst_isd_as(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.hidden_segment.v1.HiddenSegmentsRequest)
  return target;
}

::size_t HiddenSegmentsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.hidden_segment.v1.HiddenSegmentsRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint64 group_ids = 1;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::UInt64Size(
        this->_internal_group_ids())
    ;
    _impl_._group_ids_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // uint64 dst_isd_as = 2;
  if (this->_internal_dst_isd_as() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_dst_isd_as());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData HiddenSegmentsRequest::_class_data_ = {
    HiddenSegmentsRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* HiddenSegmentsRequest::GetClassData() const {
  return &_class_data_;
}

void HiddenSegmentsRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<HiddenSegmentsRequest*>(&to_msg);
  auto& from = static_cast<const HiddenSegmentsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.hidden_segment.v1.HiddenSegmentsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_group_ids()->MergeFrom(from._internal_group_ids());
  if (from._internal_dst_isd_as() != 0) {
    _this->_internal_set_dst_isd_as(from._internal_dst_isd_as());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HiddenSegmentsRequest::CopyFrom(const HiddenSegmentsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.hidden_segment.v1.HiddenSegmentsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool HiddenSegmentsRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* HiddenSegmentsRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void HiddenSegmentsRequest::InternalSwap(HiddenSegmentsRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.group_ids_.InternalSwap(&other->_impl_.group_ids_);
        swap(_impl_.dst_isd_as_, other->_impl_.dst_isd_as_);
}

::google::protobuf::Metadata HiddenSegmentsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[5]);
}
// ===================================================================

HiddenSegmentsResponse_SegmentsEntry_DoNotUse::HiddenSegmentsResponse_SegmentsEntry_DoNotUse() {}
HiddenSegmentsResponse_SegmentsEntry_DoNotUse::HiddenSegmentsResponse_SegmentsEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
::google::protobuf::Metadata HiddenSegmentsResponse_SegmentsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[6]);
}
// ===================================================================

class HiddenSegmentsResponse::_Internal {
 public:
};

HiddenSegmentsResponse::HiddenSegmentsResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.hidden_segment.v1.HiddenSegmentsResponse)
}
inline PROTOBUF_NDEBUG_INLINE HiddenSegmentsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : segments_{visibility, arena, from.segments_},
        _cached_size_{0} {}

HiddenSegmentsResponse::HiddenSegmentsResponse(
    ::google::protobuf::Arena* arena,
    const HiddenSegmentsResponse& from)
    : ::google::protobuf::Message(arena) {
  HiddenSegmentsResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:proto.hidden_segment.v1.HiddenSegmentsResponse)
}
inline PROTOBUF_NDEBUG_INLINE HiddenSegmentsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : segments_{visibility, arena},
        _cached_size_{0} {}

inline void HiddenSegmentsResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
HiddenSegmentsResponse::~HiddenSegmentsResponse() {
  // @@protoc_insertion_point(destructor:proto.hidden_segment.v1.HiddenSegmentsResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HiddenSegmentsResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void HiddenSegmentsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.hidden_segment.v1.HiddenSegmentsResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.segments_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* HiddenSegmentsResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 0, 2> HiddenSegmentsResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_HiddenSegmentsResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
    {PROTOBUF_FIELD_OFFSET(HiddenSegmentsResponse, _impl_.segments_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(HiddenSegmentsResponse()._impl_.segments_)>(
        1, 0, 0, 5,
        11)},
    {::_pbi::TcParser::CreateInArenaStorageCb<::proto::hidden_segment::v1::Segments>},
  }}, {{
  }},
};

::uint8_t* HiddenSegmentsResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.hidden_segment.v1.HiddenSegmentsResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
  if (!_internal_segments().empty()) {
    using MapType = ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>;
    using WireHelper = _pbi::MapEntryFuncs<::int32_t, ::proto::hidden_segment::v1::Segments,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = _internal_segments();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.hidden_segment.v1.HiddenSegmentsResponse)
  return target;
}

::size_t HiddenSegmentsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.hidden_segment.v1.HiddenSegmentsResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_segments_size());
  for (const auto& entry : _internal_segments()) {
    total_size += _pbi::MapEntryFuncs<::int32_t, ::proto::hidden_segment::v1::Segments,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData HiddenSegmentsResponse::_class_data_ = {
    HiddenSegmentsResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* HiddenSegmentsResponse::GetClassData() const {
  return &_class_data_;
}

void HiddenSegmentsResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<HiddenSegmentsResponse*>(&to_msg);
  auto& from = static_cast<const HiddenSegmentsResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.hidden_segment.v1.HiddenSegmentsResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.segments_.MergeFrom(from._impl_.segments_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HiddenSegmentsResponse::CopyFrom(const HiddenSegmentsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.hidden_segment.v1.HiddenSegmentsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool HiddenSegmentsResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* HiddenSegmentsResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void HiddenSegmentsResponse::InternalSwap(HiddenSegmentsResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.segments_.InternalSwap(&other->_impl_.segments_);
}

::google::protobuf::Metadata HiddenSegmentsResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[7]);
}
// ===================================================================

class AuthoritativeHiddenSegmentsRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<AuthoritativeHiddenSegmentsRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AuthoritativeHiddenSegmentsRequest, _impl_._has_bits_);
  static const ::proto::crypto::v1::SignedMessage& signed_request(const AuthoritativeHiddenSegmentsRequest* msg);
  static void set_has_signed_request(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::proto::crypto::v1::SignedMessage& AuthoritativeHiddenSegmentsRequest::_Internal::signed_request(const AuthoritativeHiddenSegmentsRequest* msg) {
  return *msg->_impl_.signed_request_;
}
void AuthoritativeHiddenSegmentsRequest::clear_signed_request() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.signed_request_ != nullptr) _impl_.signed_request_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
AuthoritativeHiddenSegmentsRequest::AuthoritativeHiddenSegmentsRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthoritativeHiddenSegmentsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

AuthoritativeHiddenSegmentsRequest::AuthoritativeHiddenSegmentsRequest(
    ::google::protobuf::Arena* arena,
    const AuthoritativeHiddenSegmentsRequest& from)
    : ::google::protobuf::Message(arena) {
  AuthoritativeHiddenSegmentsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.signed_request_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::proto::crypto::v1::SignedMessage>(arena, *from._impl_.signed_request_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthoritativeHiddenSegmentsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AuthoritativeHiddenSegmentsRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.signed_request_ = {};
}
AuthoritativeHiddenSegmentsRequest::~AuthoritativeHiddenSegmentsRequest() {
  // @@protoc_insertion_point(destructor:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthoritativeHiddenSegmentsRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete _impl_.signed_request_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AuthoritativeHiddenSegmentsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.signed_request_ != nullptr);
    _impl_.signed_request_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthoritativeHiddenSegmentsRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> AuthoritativeHiddenSegmentsRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AuthoritativeHiddenSegmentsRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AuthoritativeHiddenSegmentsRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .proto.crypto.v1.SignedMessage signed_request = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(AuthoritativeHiddenSegmentsRequest, _impl_.signed_request_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .proto.crypto.v1.SignedMessage signed_request = 1;
    {PROTOBUF_FIELD_OFFSET(AuthoritativeHiddenSegmentsRequest, _impl_.signed_request_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::proto::crypto::v1::SignedMessage>()},
  }}, {{
  }},
};

::uint8_t* AuthoritativeHiddenSegmentsRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .proto.crypto.v1.SignedMessage signed_request = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::signed_request(this),
        _Internal::signed_request(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
  return target;
}

::size_t AuthoritativeHiddenSegmentsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .proto.crypto.v1.SignedMessage signed_request = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.signed_request_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AuthoritativeHiddenSegmentsRequest::_class_data_ = {
    AuthoritativeHiddenSegmentsRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AuthoritativeHiddenSegmentsRequest::GetClassData() const {
  return &_class_data_;
}

void AuthoritativeHiddenSegmentsRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthoritativeHiddenSegmentsRequest*>(&to_msg);
  auto& from = static_cast<const AuthoritativeHiddenSegmentsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_signed_request()->::proto::crypto::v1::SignedMessage::MergeFrom(
        from._internal_signed_request());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthoritativeHiddenSegmentsRequest::CopyFrom(const AuthoritativeHiddenSegmentsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthoritativeHiddenSegmentsRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AuthoritativeHiddenSegmentsRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AuthoritativeHiddenSegmentsRequest::InternalSwap(AuthoritativeHiddenSegmentsRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.signed_request_, other->_impl_.signed_request_);
}

::google::protobuf::Metadata AuthoritativeHiddenSegmentsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[8]);
}
// ===================================================================

AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse::AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse() {}
AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse::AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
::google::protobuf::Metadata AuthoritativeHiddenSegmentsResponse_SegmentsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[9]);
}
// ===================================================================

class AuthoritativeHiddenSegmentsResponse::_Internal {
 public:
};

AuthoritativeHiddenSegmentsResponse::AuthoritativeHiddenSegmentsResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
}
inline PROTOBUF_NDEBUG_INLINE AuthoritativeHiddenSegmentsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : segments_{visibility, arena, from.segments_},
        _cached_size_{0} {}

AuthoritativeHiddenSegmentsResponse::AuthoritativeHiddenSegmentsResponse(
    ::google::protobuf::Arena* arena,
    const AuthoritativeHiddenSegmentsResponse& from)
    : ::google::protobuf::Message(arena) {
  AuthoritativeHiddenSegmentsResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
}
inline PROTOBUF_NDEBUG_INLINE AuthoritativeHiddenSegmentsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : segments_{visibility, arena},
        _cached_size_{0} {}

inline void AuthoritativeHiddenSegmentsResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AuthoritativeHiddenSegmentsResponse::~AuthoritativeHiddenSegmentsResponse() {
  // @@protoc_insertion_point(destructor:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthoritativeHiddenSegmentsResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AuthoritativeHiddenSegmentsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.segments_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthoritativeHiddenSegmentsResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 0, 2> AuthoritativeHiddenSegmentsResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AuthoritativeHiddenSegmentsResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
    {PROTOBUF_FIELD_OFFSET(AuthoritativeHiddenSegmentsResponse, _impl_.segments_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(AuthoritativeHiddenSegmentsResponse()._impl_.segments_)>(
        1, 0, 0, 5,
        11)},
    {::_pbi::TcParser::CreateInArenaStorageCb<::proto::hidden_segment::v1::Segments>},
  }}, {{
  }},
};

::uint8_t* AuthoritativeHiddenSegmentsResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
  if (!_internal_segments().empty()) {
    using MapType = ::google::protobuf::Map<::int32_t, ::proto::hidden_segment::v1::Segments>;
    using WireHelper = _pbi::MapEntryFuncs<::int32_t, ::proto::hidden_segment::v1::Segments,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = _internal_segments();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
  return target;
}

::size_t AuthoritativeHiddenSegmentsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, .proto.hidden_segment.v1.Segments> segments = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_segments_size());
  for (const auto& entry : _internal_segments()) {
    total_size += _pbi::MapEntryFuncs<::int32_t, ::proto::hidden_segment::v1::Segments,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AuthoritativeHiddenSegmentsResponse::_class_data_ = {
    AuthoritativeHiddenSegmentsResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AuthoritativeHiddenSegmentsResponse::GetClassData() const {
  return &_class_data_;
}

void AuthoritativeHiddenSegmentsResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthoritativeHiddenSegmentsResponse*>(&to_msg);
  auto& from = static_cast<const AuthoritativeHiddenSegmentsResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.segments_.MergeFrom(from._impl_.segments_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthoritativeHiddenSegmentsResponse::CopyFrom(const AuthoritativeHiddenSegmentsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.hidden_segment.v1.AuthoritativeHiddenSegmentsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthoritativeHiddenSegmentsResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AuthoritativeHiddenSegmentsResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AuthoritativeHiddenSegmentsResponse::InternalSwap(AuthoritativeHiddenSegmentsResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.segments_.InternalSwap(&other->_impl_.segments_);
}

::google::protobuf::Metadata AuthoritativeHiddenSegmentsResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_getter, &descriptor_table_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto_once,
      file_level_metadata_proto_2fhidden_5fsegment_2fv1_2fhidden_5fsegment_2eproto[10]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace hidden_segment
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
