// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/control_plane/v1/cppki.proto

#include "proto/control_plane/v1/cppki.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {
namespace control_plane {
namespace v1 {

inline constexpr VerificationKeyID::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : subject_key_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        isd_as_{::uint64_t{0u}},
        trc_base_{::uint64_t{0u}},
        trc_serial_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR VerificationKeyID::VerificationKeyID(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct VerificationKeyIDDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VerificationKeyIDDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VerificationKeyIDDefaultTypeInternal() {}
  union {
    VerificationKeyID _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VerificationKeyIDDefaultTypeInternal _VerificationKeyID_default_instance_;

inline constexpr TRCResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : trc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TRCResponse::TRCResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TRCResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TRCResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TRCResponseDefaultTypeInternal() {}
  union {
    TRCResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TRCResponseDefaultTypeInternal _TRCResponse_default_instance_;

inline constexpr TRCRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : base_{::uint64_t{0u}},
        serial_{::uint64_t{0u}},
        isd_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TRCRequest::TRCRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TRCRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TRCRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TRCRequestDefaultTypeInternal() {}
  union {
    TRCRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TRCRequestDefaultTypeInternal _TRCRequest_default_instance_;

inline constexpr Chain::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : as_cert_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ca_cert_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Chain::Chain(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ChainDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChainDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChainDefaultTypeInternal() {}
  union {
    Chain _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChainDefaultTypeInternal _Chain_default_instance_;

inline constexpr ChainsResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : chains_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ChainsResponse::ChainsResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ChainsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChainsResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChainsResponseDefaultTypeInternal() {}
  union {
    ChainsResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChainsResponseDefaultTypeInternal _ChainsResponse_default_instance_;

inline constexpr ChainsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        subject_key_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        date_{nullptr},
        isd_as_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR ChainsRequest::ChainsRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ChainsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChainsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChainsRequestDefaultTypeInternal() {}
  union {
    ChainsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChainsRequestDefaultTypeInternal _ChainsRequest_default_instance_;
}  // namespace v1
}  // namespace control_plane
}  // namespace proto
static ::_pb::Metadata file_level_metadata_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto[6];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto = nullptr;
const ::uint32_t TableStruct_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::ChainsRequest, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::ChainsRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::ChainsRequest, _impl_.isd_as_),
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::ChainsRequest, _impl_.subject_key_id_),
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::ChainsRequest, _impl_.date_),
    ~0u,
    ~0u,
    0,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::ChainsResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::ChainsResponse, _impl_.chains_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::Chain, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::Chain, _impl_.as_cert_),
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::Chain, _impl_.ca_cert_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::TRCRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::TRCRequest, _impl_.isd_),
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::TRCRequest, _impl_.base_),
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::TRCRequest, _impl_.serial_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::TRCResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::TRCResponse, _impl_.trc_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::VerificationKeyID, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::VerificationKeyID, _impl_.isd_as_),
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::VerificationKeyID, _impl_.subject_key_id_),
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::VerificationKeyID, _impl_.trc_base_),
    PROTOBUF_FIELD_OFFSET(::proto::control_plane::v1::VerificationKeyID, _impl_.trc_serial_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::proto::control_plane::v1::ChainsRequest)},
        {14, -1, -1, sizeof(::proto::control_plane::v1::ChainsResponse)},
        {23, -1, -1, sizeof(::proto::control_plane::v1::Chain)},
        {33, -1, -1, sizeof(::proto::control_plane::v1::TRCRequest)},
        {44, -1, -1, sizeof(::proto::control_plane::v1::TRCResponse)},
        {53, -1, -1, sizeof(::proto::control_plane::v1::VerificationKeyID)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::proto::control_plane::v1::_ChainsRequest_default_instance_._instance,
    &::proto::control_plane::v1::_ChainsResponse_default_instance_._instance,
    &::proto::control_plane::v1::_Chain_default_instance_._instance,
    &::proto::control_plane::v1::_TRCRequest_default_instance_._instance,
    &::proto::control_plane::v1::_TRCResponse_default_instance_._instance,
    &::proto::control_plane::v1::_VerificationKeyID_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\"proto/control_plane/v1/cppki.proto\022\026pr"
    "oto.control_plane.v1\032\037google/protobuf/ti"
    "mestamp.proto\"a\n\rChainsRequest\022\016\n\006isd_as"
    "\030\001 \001(\004\022\026\n\016subject_key_id\030\002 \001(\014\022(\n\004date\030\003"
    " \001(\0132\032.google.protobuf.Timestamp\"\?\n\016Chai"
    "nsResponse\022-\n\006chains\030\001 \003(\0132\035.proto.contr"
    "ol_plane.v1.Chain\")\n\005Chain\022\017\n\007as_cert\030\001 "
    "\001(\014\022\017\n\007ca_cert\030\002 \001(\014\"7\n\nTRCRequest\022\013\n\003is"
    "d\030\001 \001(\r\022\014\n\004base\030\002 \001(\004\022\016\n\006serial\030\003 \001(\004\"\032\n"
    "\013TRCResponse\022\013\n\003trc\030\001 \001(\014\"a\n\021Verificatio"
    "nKeyID\022\016\n\006isd_as\030\001 \001(\004\022\026\n\016subject_key_id"
    "\030\002 \001(\014\022\020\n\010trc_base\030\003 \001(\004\022\022\n\ntrc_serial\030\004"
    " \001(\0042\303\001\n\024TrustMaterialService\022Y\n\006Chains\022"
    "%.proto.control_plane.v1.ChainsRequest\032&"
    ".proto.control_plane.v1.ChainsResponse\"\000"
    "\022P\n\003TRC\022\".proto.control_plane.v1.TRCRequ"
    "est\032#.proto.control_plane.v1.TRCResponse"
    "\"\000B5Z3github.com/scionproto/scion/pkg/pr"
    "oto/control_planeb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto = {
    false,
    false,
    745,
    descriptor_table_protodef_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto,
    "proto/control_plane/v1/cppki.proto",
    &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_once,
    descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_deps,
    1,
    6,
    schemas,
    file_default_instances,
    TableStruct_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto::offsets,
    file_level_metadata_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto,
    file_level_enum_descriptors_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto,
    file_level_service_descriptors_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_getter() {
  return &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto(&descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto);
namespace proto {
namespace control_plane {
namespace v1 {
// ===================================================================

class ChainsRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<ChainsRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_._has_bits_);
  static const ::google::protobuf::Timestamp& date(const ChainsRequest* msg);
  static void set_has_date(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Timestamp& ChainsRequest::_Internal::date(const ChainsRequest* msg) {
  return *msg->_impl_.date_;
}
void ChainsRequest::clear_date() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.date_ != nullptr) _impl_.date_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
ChainsRequest::ChainsRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.control_plane.v1.ChainsRequest)
}
inline PROTOBUF_NDEBUG_INLINE ChainsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        subject_key_id_(arena, from.subject_key_id_) {}

ChainsRequest::ChainsRequest(
    ::google::protobuf::Arena* arena,
    const ChainsRequest& from)
    : ::google::protobuf::Message(arena) {
  ChainsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.date_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Timestamp>(arena, *from._impl_.date_)
                : nullptr;
  _impl_.isd_as_ = from._impl_.isd_as_;

  // @@protoc_insertion_point(copy_constructor:proto.control_plane.v1.ChainsRequest)
}
inline PROTOBUF_NDEBUG_INLINE ChainsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        subject_key_id_(arena) {}

inline void ChainsRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, date_),
           0,
           offsetof(Impl_, isd_as_) -
               offsetof(Impl_, date_) +
               sizeof(Impl_::isd_as_));
}
ChainsRequest::~ChainsRequest() {
  // @@protoc_insertion_point(destructor:proto.control_plane.v1.ChainsRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ChainsRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.subject_key_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.date_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ChainsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.control_plane.v1.ChainsRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.subject_key_id_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.date_ != nullptr);
    _impl_.date_->Clear();
  }
  _impl_.isd_as_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ChainsRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> ChainsRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ChainsRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 isd_as = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ChainsRequest, _impl_.isd_as_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_.isd_as_)}},
    // bytes subject_key_id = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_.subject_key_id_)}},
    // .google.protobuf.Timestamp date = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_.date_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 isd_as = 1;
    {PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_.isd_as_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bytes subject_key_id = 2;
    {PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_.subject_key_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // .google.protobuf.Timestamp date = 3;
    {PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_.date_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
  }},
};

::uint8_t* ChainsRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.control_plane.v1.ChainsRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 isd_as = 1;
  if (this->_internal_isd_as() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_isd_as(), target);
  }

  // bytes subject_key_id = 2;
  if (!this->_internal_subject_key_id().empty()) {
    const std::string& _s = this->_internal_subject_key_id();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Timestamp date = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::date(this),
        _Internal::date(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.control_plane.v1.ChainsRequest)
  return target;
}

::size_t ChainsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.control_plane.v1.ChainsRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes subject_key_id = 2;
  if (!this->_internal_subject_key_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_subject_key_id());
  }

  // .google.protobuf.Timestamp date = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.date_);
  }

  // uint64 isd_as = 1;
  if (this->_internal_isd_as() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_isd_as());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ChainsRequest::_class_data_ = {
    ChainsRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ChainsRequest::GetClassData() const {
  return &_class_data_;
}

void ChainsRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ChainsRequest*>(&to_msg);
  auto& from = static_cast<const ChainsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.control_plane.v1.ChainsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_subject_key_id().empty()) {
    _this->_internal_set_subject_key_id(from._internal_subject_key_id());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_date()->::google::protobuf::Timestamp::MergeFrom(
        from._internal_date());
  }
  if (from._internal_isd_as() != 0) {
    _this->_internal_set_isd_as(from._internal_isd_as());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChainsRequest::CopyFrom(const ChainsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.control_plane.v1.ChainsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ChainsRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ChainsRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ChainsRequest::InternalSwap(ChainsRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.subject_key_id_, &other->_impl_.subject_key_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_.isd_as_)
      + sizeof(ChainsRequest::_impl_.isd_as_)
      - PROTOBUF_FIELD_OFFSET(ChainsRequest, _impl_.date_)>(
          reinterpret_cast<char*>(&_impl_.date_),
          reinterpret_cast<char*>(&other->_impl_.date_));
}

::google::protobuf::Metadata ChainsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_getter, &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_once,
      file_level_metadata_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto[0]);
}
// ===================================================================

class ChainsResponse::_Internal {
 public:
};

ChainsResponse::ChainsResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.control_plane.v1.ChainsResponse)
}
inline PROTOBUF_NDEBUG_INLINE ChainsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : chains_{visibility, arena, from.chains_},
        _cached_size_{0} {}

ChainsResponse::ChainsResponse(
    ::google::protobuf::Arena* arena,
    const ChainsResponse& from)
    : ::google::protobuf::Message(arena) {
  ChainsResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:proto.control_plane.v1.ChainsResponse)
}
inline PROTOBUF_NDEBUG_INLINE ChainsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : chains_{visibility, arena},
        _cached_size_{0} {}

inline void ChainsResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ChainsResponse::~ChainsResponse() {
  // @@protoc_insertion_point(destructor:proto.control_plane.v1.ChainsResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ChainsResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ChainsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.control_plane.v1.ChainsResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chains_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ChainsResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ChainsResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ChainsResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .proto.control_plane.v1.Chain chains = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ChainsResponse, _impl_.chains_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .proto.control_plane.v1.Chain chains = 1;
    {PROTOBUF_FIELD_OFFSET(ChainsResponse, _impl_.chains_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::proto::control_plane::v1::Chain>()},
  }}, {{
  }},
};

::uint8_t* ChainsResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.control_plane.v1.ChainsResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .proto.control_plane.v1.Chain chains = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_chains_size()); i < n; i++) {
    const auto& repfield = this->_internal_chains().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.control_plane.v1.ChainsResponse)
  return target;
}

::size_t ChainsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.control_plane.v1.ChainsResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .proto.control_plane.v1.Chain chains = 1;
  total_size += 1UL * this->_internal_chains_size();
  for (const auto& msg : this->_internal_chains()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ChainsResponse::_class_data_ = {
    ChainsResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ChainsResponse::GetClassData() const {
  return &_class_data_;
}

void ChainsResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ChainsResponse*>(&to_msg);
  auto& from = static_cast<const ChainsResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.control_plane.v1.ChainsResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_chains()->MergeFrom(
      from._internal_chains());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChainsResponse::CopyFrom(const ChainsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.control_plane.v1.ChainsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ChainsResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ChainsResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ChainsResponse::InternalSwap(ChainsResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.chains_.InternalSwap(&other->_impl_.chains_);
}

::google::protobuf::Metadata ChainsResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_getter, &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_once,
      file_level_metadata_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto[1]);
}
// ===================================================================

class Chain::_Internal {
 public:
};

Chain::Chain(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.control_plane.v1.Chain)
}
inline PROTOBUF_NDEBUG_INLINE Chain::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : as_cert_(arena, from.as_cert_),
        ca_cert_(arena, from.ca_cert_),
        _cached_size_{0} {}

Chain::Chain(
    ::google::protobuf::Arena* arena,
    const Chain& from)
    : ::google::protobuf::Message(arena) {
  Chain* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:proto.control_plane.v1.Chain)
}
inline PROTOBUF_NDEBUG_INLINE Chain::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : as_cert_(arena),
        ca_cert_(arena),
        _cached_size_{0} {}

inline void Chain::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Chain::~Chain() {
  // @@protoc_insertion_point(destructor:proto.control_plane.v1.Chain)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Chain::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.as_cert_.Destroy();
  _impl_.ca_cert_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Chain::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.control_plane.v1.Chain)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.as_cert_.ClearToEmpty();
  _impl_.ca_cert_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Chain::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Chain::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Chain_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes ca_cert = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Chain, _impl_.ca_cert_)}},
    // bytes as_cert = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Chain, _impl_.as_cert_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes as_cert = 1;
    {PROTOBUF_FIELD_OFFSET(Chain, _impl_.as_cert_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes ca_cert = 2;
    {PROTOBUF_FIELD_OFFSET(Chain, _impl_.ca_cert_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Chain::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.control_plane.v1.Chain)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes as_cert = 1;
  if (!this->_internal_as_cert().empty()) {
    const std::string& _s = this->_internal_as_cert();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // bytes ca_cert = 2;
  if (!this->_internal_ca_cert().empty()) {
    const std::string& _s = this->_internal_ca_cert();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.control_plane.v1.Chain)
  return target;
}

::size_t Chain::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.control_plane.v1.Chain)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes as_cert = 1;
  if (!this->_internal_as_cert().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_as_cert());
  }

  // bytes ca_cert = 2;
  if (!this->_internal_ca_cert().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_ca_cert());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Chain::_class_data_ = {
    Chain::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Chain::GetClassData() const {
  return &_class_data_;
}

void Chain::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Chain*>(&to_msg);
  auto& from = static_cast<const Chain&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.control_plane.v1.Chain)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_as_cert().empty()) {
    _this->_internal_set_as_cert(from._internal_as_cert());
  }
  if (!from._internal_ca_cert().empty()) {
    _this->_internal_set_ca_cert(from._internal_ca_cert());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Chain::CopyFrom(const Chain& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.control_plane.v1.Chain)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Chain::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Chain::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Chain::InternalSwap(Chain* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.as_cert_, &other->_impl_.as_cert_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ca_cert_, &other->_impl_.ca_cert_, arena);
}

::google::protobuf::Metadata Chain::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_getter, &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_once,
      file_level_metadata_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto[2]);
}
// ===================================================================

class TRCRequest::_Internal {
 public:
};

TRCRequest::TRCRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.control_plane.v1.TRCRequest)
}
TRCRequest::TRCRequest(
    ::google::protobuf::Arena* arena, const TRCRequest& from)
    : TRCRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE TRCRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void TRCRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, base_),
           0,
           offsetof(Impl_, isd_) -
               offsetof(Impl_, base_) +
               sizeof(Impl_::isd_));
}
TRCRequest::~TRCRequest() {
  // @@protoc_insertion_point(destructor:proto.control_plane.v1.TRCRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TRCRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void TRCRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.control_plane.v1.TRCRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.base_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.isd_) -
      reinterpret_cast<char*>(&_impl_.base_)) + sizeof(_impl_.isd_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* TRCRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> TRCRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_TRCRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 isd = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TRCRequest, _impl_.isd_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(TRCRequest, _impl_.isd_)}},
    // uint64 base = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TRCRequest, _impl_.base_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TRCRequest, _impl_.base_)}},
    // uint64 serial = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TRCRequest, _impl_.serial_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(TRCRequest, _impl_.serial_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 isd = 1;
    {PROTOBUF_FIELD_OFFSET(TRCRequest, _impl_.isd_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint64 base = 2;
    {PROTOBUF_FIELD_OFFSET(TRCRequest, _impl_.base_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 serial = 3;
    {PROTOBUF_FIELD_OFFSET(TRCRequest, _impl_.serial_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* TRCRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.control_plane.v1.TRCRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 isd = 1;
  if (this->_internal_isd() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_isd(), target);
  }

  // uint64 base = 2;
  if (this->_internal_base() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_base(), target);
  }

  // uint64 serial = 3;
  if (this->_internal_serial() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_serial(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.control_plane.v1.TRCRequest)
  return target;
}

::size_t TRCRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.control_plane.v1.TRCRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 base = 2;
  if (this->_internal_base() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_base());
  }

  // uint64 serial = 3;
  if (this->_internal_serial() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_serial());
  }

  // uint32 isd = 1;
  if (this->_internal_isd() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_isd());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData TRCRequest::_class_data_ = {
    TRCRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* TRCRequest::GetClassData() const {
  return &_class_data_;
}

void TRCRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<TRCRequest*>(&to_msg);
  auto& from = static_cast<const TRCRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.control_plane.v1.TRCRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_base() != 0) {
    _this->_internal_set_base(from._internal_base());
  }
  if (from._internal_serial() != 0) {
    _this->_internal_set_serial(from._internal_serial());
  }
  if (from._internal_isd() != 0) {
    _this->_internal_set_isd(from._internal_isd());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TRCRequest::CopyFrom(const TRCRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.control_plane.v1.TRCRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TRCRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* TRCRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void TRCRequest::InternalSwap(TRCRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TRCRequest, _impl_.isd_)
      + sizeof(TRCRequest::_impl_.isd_)
      - PROTOBUF_FIELD_OFFSET(TRCRequest, _impl_.base_)>(
          reinterpret_cast<char*>(&_impl_.base_),
          reinterpret_cast<char*>(&other->_impl_.base_));
}

::google::protobuf::Metadata TRCRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_getter, &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_once,
      file_level_metadata_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto[3]);
}
// ===================================================================

class TRCResponse::_Internal {
 public:
};

TRCResponse::TRCResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.control_plane.v1.TRCResponse)
}
inline PROTOBUF_NDEBUG_INLINE TRCResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : trc_(arena, from.trc_),
        _cached_size_{0} {}

TRCResponse::TRCResponse(
    ::google::protobuf::Arena* arena,
    const TRCResponse& from)
    : ::google::protobuf::Message(arena) {
  TRCResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:proto.control_plane.v1.TRCResponse)
}
inline PROTOBUF_NDEBUG_INLINE TRCResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : trc_(arena),
        _cached_size_{0} {}

inline void TRCResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TRCResponse::~TRCResponse() {
  // @@protoc_insertion_point(destructor:proto.control_plane.v1.TRCResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TRCResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.trc_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void TRCResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.control_plane.v1.TRCResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.trc_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* TRCResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> TRCResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_TRCResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes trc = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TRCResponse, _impl_.trc_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes trc = 1;
    {PROTOBUF_FIELD_OFFSET(TRCResponse, _impl_.trc_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* TRCResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.control_plane.v1.TRCResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes trc = 1;
  if (!this->_internal_trc().empty()) {
    const std::string& _s = this->_internal_trc();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.control_plane.v1.TRCResponse)
  return target;
}

::size_t TRCResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.control_plane.v1.TRCResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes trc = 1;
  if (!this->_internal_trc().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_trc());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData TRCResponse::_class_data_ = {
    TRCResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* TRCResponse::GetClassData() const {
  return &_class_data_;
}

void TRCResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<TRCResponse*>(&to_msg);
  auto& from = static_cast<const TRCResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.control_plane.v1.TRCResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_trc().empty()) {
    _this->_internal_set_trc(from._internal_trc());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TRCResponse::CopyFrom(const TRCResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.control_plane.v1.TRCResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TRCResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* TRCResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void TRCResponse::InternalSwap(TRCResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.trc_, &other->_impl_.trc_, arena);
}

::google::protobuf::Metadata TRCResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_getter, &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_once,
      file_level_metadata_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto[4]);
}
// ===================================================================

class VerificationKeyID::_Internal {
 public:
};

VerificationKeyID::VerificationKeyID(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.control_plane.v1.VerificationKeyID)
}
inline PROTOBUF_NDEBUG_INLINE VerificationKeyID::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : subject_key_id_(arena, from.subject_key_id_),
        _cached_size_{0} {}

VerificationKeyID::VerificationKeyID(
    ::google::protobuf::Arena* arena,
    const VerificationKeyID& from)
    : ::google::protobuf::Message(arena) {
  VerificationKeyID* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, isd_as_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, isd_as_),
           offsetof(Impl_, trc_serial_) -
               offsetof(Impl_, isd_as_) +
               sizeof(Impl_::trc_serial_));

  // @@protoc_insertion_point(copy_constructor:proto.control_plane.v1.VerificationKeyID)
}
inline PROTOBUF_NDEBUG_INLINE VerificationKeyID::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : subject_key_id_(arena),
        _cached_size_{0} {}

inline void VerificationKeyID::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, isd_as_),
           0,
           offsetof(Impl_, trc_serial_) -
               offsetof(Impl_, isd_as_) +
               sizeof(Impl_::trc_serial_));
}
VerificationKeyID::~VerificationKeyID() {
  // @@protoc_insertion_point(destructor:proto.control_plane.v1.VerificationKeyID)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void VerificationKeyID::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.subject_key_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void VerificationKeyID::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.control_plane.v1.VerificationKeyID)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.subject_key_id_.ClearToEmpty();
  ::memset(&_impl_.isd_as_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.trc_serial_) -
      reinterpret_cast<char*>(&_impl_.isd_as_)) + sizeof(_impl_.trc_serial_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* VerificationKeyID::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> VerificationKeyID::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_VerificationKeyID_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint64 trc_serial = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(VerificationKeyID, _impl_.trc_serial_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.trc_serial_)}},
    // uint64 isd_as = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(VerificationKeyID, _impl_.isd_as_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.isd_as_)}},
    // bytes subject_key_id = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.subject_key_id_)}},
    // uint64 trc_base = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(VerificationKeyID, _impl_.trc_base_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.trc_base_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 isd_as = 1;
    {PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.isd_as_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bytes subject_key_id = 2;
    {PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.subject_key_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint64 trc_base = 3;
    {PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.trc_base_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 trc_serial = 4;
    {PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.trc_serial_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* VerificationKeyID::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.control_plane.v1.VerificationKeyID)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 isd_as = 1;
  if (this->_internal_isd_as() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_isd_as(), target);
  }

  // bytes subject_key_id = 2;
  if (!this->_internal_subject_key_id().empty()) {
    const std::string& _s = this->_internal_subject_key_id();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // uint64 trc_base = 3;
  if (this->_internal_trc_base() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_trc_base(), target);
  }

  // uint64 trc_serial = 4;
  if (this->_internal_trc_serial() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        4, this->_internal_trc_serial(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.control_plane.v1.VerificationKeyID)
  return target;
}

::size_t VerificationKeyID::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.control_plane.v1.VerificationKeyID)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes subject_key_id = 2;
  if (!this->_internal_subject_key_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_subject_key_id());
  }

  // uint64 isd_as = 1;
  if (this->_internal_isd_as() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_isd_as());
  }

  // uint64 trc_base = 3;
  if (this->_internal_trc_base() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_trc_base());
  }

  // uint64 trc_serial = 4;
  if (this->_internal_trc_serial() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_trc_serial());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData VerificationKeyID::_class_data_ = {
    VerificationKeyID::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* VerificationKeyID::GetClassData() const {
  return &_class_data_;
}

void VerificationKeyID::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<VerificationKeyID*>(&to_msg);
  auto& from = static_cast<const VerificationKeyID&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.control_plane.v1.VerificationKeyID)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_subject_key_id().empty()) {
    _this->_internal_set_subject_key_id(from._internal_subject_key_id());
  }
  if (from._internal_isd_as() != 0) {
    _this->_internal_set_isd_as(from._internal_isd_as());
  }
  if (from._internal_trc_base() != 0) {
    _this->_internal_set_trc_base(from._internal_trc_base());
  }
  if (from._internal_trc_serial() != 0) {
    _this->_internal_set_trc_serial(from._internal_trc_serial());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VerificationKeyID::CopyFrom(const VerificationKeyID& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.control_plane.v1.VerificationKeyID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool VerificationKeyID::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* VerificationKeyID::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void VerificationKeyID::InternalSwap(VerificationKeyID* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.subject_key_id_, &other->_impl_.subject_key_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.trc_serial_)
      + sizeof(VerificationKeyID::_impl_.trc_serial_)
      - PROTOBUF_FIELD_OFFSET(VerificationKeyID, _impl_.isd_as_)>(
          reinterpret_cast<char*>(&_impl_.isd_as_),
          reinterpret_cast<char*>(&other->_impl_.isd_as_));
}

::google::protobuf::Metadata VerificationKeyID::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_getter, &descriptor_table_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto_once,
      file_level_metadata_proto_2fcontrol_5fplane_2fv1_2fcppki_2eproto[5]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace control_plane
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
