// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/control_plane/v1/seg.proto
// Original file comments:
// Copyright 2020 Anapaya Systems
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_proto_2fcontrol_5fplane_2fv1_2fseg_2eproto__INCLUDED
#define GRPC_proto_2fcontrol_5fplane_2fv1_2fseg_2eproto__INCLUDED

#include "proto/control_plane/v1/seg.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace proto {
namespace control_plane {
namespace v1 {

class SegmentLookupService final {
 public:
  static constexpr char const* service_full_name() {
    return "proto.control_plane.v1.SegmentLookupService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Segments returns all segments that match the request.
    virtual ::grpc::Status Segments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::proto::control_plane::v1::SegmentsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsResponse>> AsyncSegments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsResponse>>(AsyncSegmentsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsResponse>> PrepareAsyncSegments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsResponse>>(PrepareAsyncSegmentsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Segments returns all segments that match the request.
      virtual void Segments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest* request, ::proto::control_plane::v1::SegmentsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Segments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest* request, ::proto::control_plane::v1::SegmentsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsResponse>* AsyncSegmentsRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsResponse>* PrepareAsyncSegmentsRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Segments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::proto::control_plane::v1::SegmentsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsResponse>> AsyncSegments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsResponse>>(AsyncSegmentsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsResponse>> PrepareAsyncSegments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsResponse>>(PrepareAsyncSegmentsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Segments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest* request, ::proto::control_plane::v1::SegmentsResponse* response, std::function<void(::grpc::Status)>) override;
      void Segments(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest* request, ::proto::control_plane::v1::SegmentsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsResponse>* AsyncSegmentsRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsResponse>* PrepareAsyncSegmentsRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Segments_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Segments returns all segments that match the request.
    virtual ::grpc::Status Segments(::grpc::ServerContext* context, const ::proto::control_plane::v1::SegmentsRequest* request, ::proto::control_plane::v1::SegmentsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Segments : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Segments() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Segments() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Segments(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRequest* /*request*/, ::proto::control_plane::v1::SegmentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSegments(::grpc::ServerContext* context, ::proto::control_plane::v1::SegmentsRequest* request, ::grpc::ServerAsyncResponseWriter< ::proto::control_plane::v1::SegmentsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Segments<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Segments : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Segments() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::proto::control_plane::v1::SegmentsRequest, ::proto::control_plane::v1::SegmentsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::proto::control_plane::v1::SegmentsRequest* request, ::proto::control_plane::v1::SegmentsResponse* response) { return this->Segments(context, request, response); }));}
    void SetMessageAllocatorFor_Segments(
        ::grpc::MessageAllocator< ::proto::control_plane::v1::SegmentsRequest, ::proto::control_plane::v1::SegmentsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::proto::control_plane::v1::SegmentsRequest, ::proto::control_plane::v1::SegmentsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Segments() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Segments(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRequest* /*request*/, ::proto::control_plane::v1::SegmentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Segments(
      ::grpc::CallbackServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRequest* /*request*/, ::proto::control_plane::v1::SegmentsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Segments<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Segments : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Segments() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Segments() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Segments(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRequest* /*request*/, ::proto::control_plane::v1::SegmentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Segments : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Segments() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Segments() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Segments(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRequest* /*request*/, ::proto::control_plane::v1::SegmentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSegments(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Segments : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Segments() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Segments(context, request, response); }));
    }
    ~WithRawCallbackMethod_Segments() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Segments(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRequest* /*request*/, ::proto::control_plane::v1::SegmentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Segments(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Segments : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Segments() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::proto::control_plane::v1::SegmentsRequest, ::proto::control_plane::v1::SegmentsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::proto::control_plane::v1::SegmentsRequest, ::proto::control_plane::v1::SegmentsResponse>* streamer) {
                       return this->StreamedSegments(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Segments() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Segments(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRequest* /*request*/, ::proto::control_plane::v1::SegmentsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSegments(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::proto::control_plane::v1::SegmentsRequest,::proto::control_plane::v1::SegmentsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Segments<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Segments<Service > StreamedService;
};

class SegmentRegistrationService final {
 public:
  static constexpr char const* service_full_name() {
    return "proto.control_plane.v1.SegmentRegistrationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // SegmentsRegistration registers segments at the remote.
    virtual ::grpc::Status SegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::proto::control_plane::v1::SegmentsRegistrationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsRegistrationResponse>> AsyncSegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsRegistrationResponse>>(AsyncSegmentsRegistrationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsRegistrationResponse>> PrepareAsyncSegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsRegistrationResponse>>(PrepareAsyncSegmentsRegistrationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // SegmentsRegistration registers segments at the remote.
      virtual void SegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest* request, ::proto::control_plane::v1::SegmentsRegistrationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest* request, ::proto::control_plane::v1::SegmentsRegistrationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsRegistrationResponse>* AsyncSegmentsRegistrationRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::SegmentsRegistrationResponse>* PrepareAsyncSegmentsRegistrationRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::proto::control_plane::v1::SegmentsRegistrationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsRegistrationResponse>> AsyncSegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsRegistrationResponse>>(AsyncSegmentsRegistrationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsRegistrationResponse>> PrepareAsyncSegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsRegistrationResponse>>(PrepareAsyncSegmentsRegistrationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest* request, ::proto::control_plane::v1::SegmentsRegistrationResponse* response, std::function<void(::grpc::Status)>) override;
      void SegmentsRegistration(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest* request, ::proto::control_plane::v1::SegmentsRegistrationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsRegistrationResponse>* AsyncSegmentsRegistrationRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::SegmentsRegistrationResponse>* PrepareAsyncSegmentsRegistrationRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SegmentsRegistration_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // SegmentsRegistration registers segments at the remote.
    virtual ::grpc::Status SegmentsRegistration(::grpc::ServerContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest* request, ::proto::control_plane::v1::SegmentsRegistrationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SegmentsRegistration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SegmentsRegistration() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SegmentsRegistration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SegmentsRegistration(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRegistrationRequest* /*request*/, ::proto::control_plane::v1::SegmentsRegistrationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSegmentsRegistration(::grpc::ServerContext* context, ::proto::control_plane::v1::SegmentsRegistrationRequest* request, ::grpc::ServerAsyncResponseWriter< ::proto::control_plane::v1::SegmentsRegistrationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SegmentsRegistration<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SegmentsRegistration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SegmentsRegistration() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::proto::control_plane::v1::SegmentsRegistrationRequest, ::proto::control_plane::v1::SegmentsRegistrationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::proto::control_plane::v1::SegmentsRegistrationRequest* request, ::proto::control_plane::v1::SegmentsRegistrationResponse* response) { return this->SegmentsRegistration(context, request, response); }));}
    void SetMessageAllocatorFor_SegmentsRegistration(
        ::grpc::MessageAllocator< ::proto::control_plane::v1::SegmentsRegistrationRequest, ::proto::control_plane::v1::SegmentsRegistrationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::proto::control_plane::v1::SegmentsRegistrationRequest, ::proto::control_plane::v1::SegmentsRegistrationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SegmentsRegistration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SegmentsRegistration(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRegistrationRequest* /*request*/, ::proto::control_plane::v1::SegmentsRegistrationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SegmentsRegistration(
      ::grpc::CallbackServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRegistrationRequest* /*request*/, ::proto::control_plane::v1::SegmentsRegistrationResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SegmentsRegistration<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SegmentsRegistration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SegmentsRegistration() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SegmentsRegistration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SegmentsRegistration(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRegistrationRequest* /*request*/, ::proto::control_plane::v1::SegmentsRegistrationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SegmentsRegistration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SegmentsRegistration() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SegmentsRegistration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SegmentsRegistration(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRegistrationRequest* /*request*/, ::proto::control_plane::v1::SegmentsRegistrationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSegmentsRegistration(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SegmentsRegistration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SegmentsRegistration() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SegmentsRegistration(context, request, response); }));
    }
    ~WithRawCallbackMethod_SegmentsRegistration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SegmentsRegistration(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRegistrationRequest* /*request*/, ::proto::control_plane::v1::SegmentsRegistrationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SegmentsRegistration(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SegmentsRegistration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SegmentsRegistration() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::proto::control_plane::v1::SegmentsRegistrationRequest, ::proto::control_plane::v1::SegmentsRegistrationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::proto::control_plane::v1::SegmentsRegistrationRequest, ::proto::control_plane::v1::SegmentsRegistrationResponse>* streamer) {
                       return this->StreamedSegmentsRegistration(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SegmentsRegistration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SegmentsRegistration(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::SegmentsRegistrationRequest* /*request*/, ::proto::control_plane::v1::SegmentsRegistrationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSegmentsRegistration(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::proto::control_plane::v1::SegmentsRegistrationRequest,::proto::control_plane::v1::SegmentsRegistrationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SegmentsRegistration<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SegmentsRegistration<Service > StreamedService;
};

class SegmentCreationService final {
 public:
  static constexpr char const* service_full_name() {
    return "proto.control_plane.v1.SegmentCreationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Beacon sends a beacon to the remote.
    virtual ::grpc::Status Beacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::proto::control_plane::v1::BeaconResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::BeaconResponse>> AsyncBeacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::BeaconResponse>>(AsyncBeaconRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::BeaconResponse>> PrepareAsyncBeacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::BeaconResponse>>(PrepareAsyncBeaconRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Beacon sends a beacon to the remote.
      virtual void Beacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest* request, ::proto::control_plane::v1::BeaconResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Beacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest* request, ::proto::control_plane::v1::BeaconResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::BeaconResponse>* AsyncBeaconRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::control_plane::v1::BeaconResponse>* PrepareAsyncBeaconRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Beacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::proto::control_plane::v1::BeaconResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::BeaconResponse>> AsyncBeacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::BeaconResponse>>(AsyncBeaconRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::BeaconResponse>> PrepareAsyncBeacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::BeaconResponse>>(PrepareAsyncBeaconRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Beacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest* request, ::proto::control_plane::v1::BeaconResponse* response, std::function<void(::grpc::Status)>) override;
      void Beacon(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest* request, ::proto::control_plane::v1::BeaconResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::BeaconResponse>* AsyncBeaconRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::proto::control_plane::v1::BeaconResponse>* PrepareAsyncBeaconRaw(::grpc::ClientContext* context, const ::proto::control_plane::v1::BeaconRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Beacon_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Beacon sends a beacon to the remote.
    virtual ::grpc::Status Beacon(::grpc::ServerContext* context, const ::proto::control_plane::v1::BeaconRequest* request, ::proto::control_plane::v1::BeaconResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Beacon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Beacon() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Beacon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Beacon(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::BeaconRequest* /*request*/, ::proto::control_plane::v1::BeaconResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBeacon(::grpc::ServerContext* context, ::proto::control_plane::v1::BeaconRequest* request, ::grpc::ServerAsyncResponseWriter< ::proto::control_plane::v1::BeaconResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Beacon<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Beacon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Beacon() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::proto::control_plane::v1::BeaconRequest, ::proto::control_plane::v1::BeaconResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::proto::control_plane::v1::BeaconRequest* request, ::proto::control_plane::v1::BeaconResponse* response) { return this->Beacon(context, request, response); }));}
    void SetMessageAllocatorFor_Beacon(
        ::grpc::MessageAllocator< ::proto::control_plane::v1::BeaconRequest, ::proto::control_plane::v1::BeaconResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::proto::control_plane::v1::BeaconRequest, ::proto::control_plane::v1::BeaconResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Beacon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Beacon(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::BeaconRequest* /*request*/, ::proto::control_plane::v1::BeaconResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Beacon(
      ::grpc::CallbackServerContext* /*context*/, const ::proto::control_plane::v1::BeaconRequest* /*request*/, ::proto::control_plane::v1::BeaconResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Beacon<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Beacon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Beacon() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Beacon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Beacon(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::BeaconRequest* /*request*/, ::proto::control_plane::v1::BeaconResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Beacon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Beacon() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Beacon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Beacon(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::BeaconRequest* /*request*/, ::proto::control_plane::v1::BeaconResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBeacon(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Beacon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Beacon() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Beacon(context, request, response); }));
    }
    ~WithRawCallbackMethod_Beacon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Beacon(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::BeaconRequest* /*request*/, ::proto::control_plane::v1::BeaconResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Beacon(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Beacon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Beacon() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::proto::control_plane::v1::BeaconRequest, ::proto::control_plane::v1::BeaconResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::proto::control_plane::v1::BeaconRequest, ::proto::control_plane::v1::BeaconResponse>* streamer) {
                       return this->StreamedBeacon(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Beacon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Beacon(::grpc::ServerContext* /*context*/, const ::proto::control_plane::v1::BeaconRequest* /*request*/, ::proto::control_plane::v1::BeaconResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBeacon(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::proto::control_plane::v1::BeaconRequest,::proto::control_plane::v1::BeaconResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Beacon<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Beacon<Service > StreamedService;
};

}  // namespace v1
}  // namespace control_plane
}  // namespace proto


#endif  // GRPC_proto_2fcontrol_5fplane_2fv1_2fseg_2eproto__INCLUDED
